### ISSUE TITLE
com.ge.research.sadl.jena manifest

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#10]
I ran into git issues again and had to create a new local repo and clone to get the latest changes checked in by Sven. In order to get com.ge.research.sadl.jena to build, I had to make the following changes to the MANIFEST.MF file:

 (remove) - org.eclipse.emf;bundle-version="2.6.0",
 (remove) - org.eclipse.equinox.common;bundle-version="3.7.0"
 (add) + org.eclipse.equinox.registry

what's that all about?

**Comment by svenefftinge** [comment]
I think you are using a different version of eclipse than I do. We should define a target platform. This can and should be done along with the automatic oomph setup I mentioned yesterday during the phone call.

**Comment by svenefftinge** [comment]
we now have a target platform
