### ISSUE TITLE
Check-boxes in custom preference pages do not return false.

### ISSUE THREAD

**Issue by nbachman** [crapo/sadlos2#107]
When a check-box in a custom preference page (SADL, Requirements) is not selected, instead of returning a false value associated with a key (e.g. "Check for ambiguous names"), the key-value ("ambigiousNameCheckOn", boolean) pair is not collected into any preference store. Therefore, the default value for a preference key is returned by function calls such as line 124 of SadlSemanticHighlightingCalculator.xtend:
![image](https://cloud.githubusercontent.com/assets/3697739/18554064/061469ba-7b31-11e6-8e13-074920052392.png)

Full call-stack to the point where the key isn't found in any preference node:
![image](https://cloud.githubusercontent.com/assets/3697739/18554149/3d4185a8-7b31-11e6-9978-3d6657ee1679.png)

For the check-box, "Check for ambiguous names", its key-value pair will appear in the "InstancePreferences" node under its properties in PreferenceService.get() if the box is checked. If the check-box is unchecked, none of the nodes processed by that method will contain any reference to our key allowing the default value, eventually, to be returned. 

Ideally, a marked check-box should return a "true" value (current behavior), and an unmarked check-box should appear in our preference collections and return a "false" value, not the default value.

**Comment by dhuebner** [comment]
@nbachman I can not reproduce the issue with the IPreferenceValuesProvider see provided tests. Also in a running product it's not reproducible.
However, I've noticed that you are heavily using  IPreferenceValuesProvider abstraction in UI bundles. As in eclipse the IPreferenceValuesProvider will be bound to the org.eclipse.xtext.ui.preferences.EclipsePreferencesProvider it will behave the same as the IPreferenceStoreAccess. IPreferenceStoreAccess has a better API to access and write preferences, I would like to suggest to use it in UI bundles.

An another note about  SadlPreferencesProvider it seems to be unused (at least I found any references to it). But also here you can safely use the IPreferenceStoreAccess:

`preferenceStoreAccess.getPreferenceStore()` 
` preferenceStoreAccess.getContextPreferenceStore(yourProject)` <- project scope

**Comment by dhuebner** [comment]
@nbachman I forgot to mention that I also added a `com.ge.research.sadl.ui.preferences.SadlPreferencesInitializer` if you would like to change the default value for the property

**Comment by nbachman** [comment]
@dhuebner Would it be possible to fix the underlying issue of check-boxes in custom preference pages not returning a false value when they are unchecked?

**Comment by dhuebner** [comment]
@nbachman 
I'm a bit confused, you said: unchecked -> "false":
> Ideally, a marked check-box should return a "true" value (current behavior), and an **unmarked** check-box should appear in our preference collections and **return a "false" value**, not the default value.

... and: unchecked -> "not false"
> check-boxes in custom preference pages **not returning a false value** when they are **unchecked**?

Please point me to a concrete case that I can reproduce? Or even better a Junit Plugin test.

**Comment by nbachman** [comment]
@dhuebner, I have updated our other repository (https://github.com/GEGlobalResearch/requirements) with our current SRL code. It currently resides in a branch called "NewRCE_Merge".

**Comment by dhuebner** [comment]
@nbachman Thanks, will start working on it

**Comment by dhuebner** [comment]
@nbachman @crapo I've pushed the changes for the requirements project. Please let me know if you have questions.  
Note that sadlos2 remain in the old state.

**Comment by nbachman** [comment]
@dhuebner I have been able to check the changes. The issue has been resolved. Thanks!
