### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by svenefftinge** [crapo/sadlos2#109]
There are several failing tests.
Some of them seem to be related to the recent change in scoping (https://github.com/crapo/sadlos2/commit/3e48c6048bcdfe00fe9362ca8b0cd370a0730533)

Andy, could you go over it and clarify if the expectations are wrong (have changed) or they fail for good reasons?

One example is com.ge.research.sadl.tests.scoping.SadlLinkingTest

**Comment by crapo** [comment]
This is the same issue as #111.
