### ISSUE TITLE
How to access preferences/project properties from projects

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#11]
It will be necessary to have access to the workspace and project preferences and project properties from within code in both com.ge.research.sadl and com.ge.research.jena. What is the best way to do this? Note that the SADL project properties will include reasoner/translator pair preferences that on a custom form created from the reasoner/translator code.

**Comment by svenefftinge** [comment]
Direct dependencies to Eclipse preferences should be avoided. Instead we should have the API for this  configuration in the runtime project (along with some default implementation) and bind an Eclipse-specific implementation from the SadlUiModule.

**Comment by crapo** [comment]
We could use some help setting this up correctly.

**Comment by svenefftinge** [comment]
This has been solve in the meantime
