### ISSUE TITLE
Commas in "with" clauses allowed in ontology definition, not allowed in expressions

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#116]
Example:
 uri "http://sadl.org/concepts.sadl" alias concepts.
  Class is a class described by reference with values of type Class,
    described by description with values of type string.
  Inst1 is a Class.
 Inst2 is a Class,
  with reference Inst1,
  with description "Hello world".
    Expr: Inst2 is (a Class,
        with reference Inst1,
        with description "arc tangent of the x over y between -1/2 Pi and 1/2 Pi").

This test case, without commas (com.ge.research.sadl.tests/src/com.ge.research.sadl.tests.InstanceCreationParserTest.testWith1) and with commas (...testWith2, ignored) have been pushed to sadlos2/master
The commas in the expression cause errors but are legal in the ontology declaration.

**Comment by crapo** [comment]
Here's another example from SADL 2 regression tests which I've added as a JUnit test testTestWithCommas in SADLParsingTest.xtend with @Ignore:
Thingy is a top-level class.
intVal describes Thingy has values of type int.
flVal describes Thingy has values of type float.
dblVal describes Thingy has values of type double.
Test: MyThingy has intVal 1, has flVal 1.0, has dblVal 1.0 .

**Comment by svenefftinge** [comment]
Fixed with https://github.com/crapo/sadlos2/commit/54600a498aeaeee0f6fac8fb240352245d7a63b8
