### ISSUE TITLE
tests project imports Jena?

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#13]
The tests project currently uses jenaModel, which is a Jena OntModel. That is fine because I can test that the OWL model was generated correctly. But does that mean that the tests project is really a jena.tests project and that there would be a different test project for a different (non-Jena) SadlModelProcessor? Just wanted to make sure that tests I'm writing in SadlModelManagerProviderTest.xtend are doing the right thing....

**Comment by svenefftinge** [comment]
Yes, that is correct. I think it is ok to have a single test project instead of one for each project. If you prefer to also separate on that level we can do.

**Comment by crapo** [comment]
No, I'm OK with one. Should we have other processors, e.g., owlAPI or Web, then tests for both would be in the test project, right?
