### ISSUE TITLE
Inference not working on Linux

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#130]
[simpletest.zip](https://github.com/crapo/sadlos2/files/613326/simpletest.zip)

**Comment by kittaakos** [comment]
Could you please clarify a bit what does 'not working' mean? I am asking because I have experienced some issue with the inferencer on OS X.

**Comment by crapo** [comment]
Sorry to be slow--holiday weekend in US. I mean that there are no inferences made. Neither OWL entailments (when appropriate Jena Model Spec is chosen) nor rule-based inferences occur. Only the assertions are present in the model.

**Comment by crapo** [comment]
The good news (I guess) is that inference is also broken on Windows, so it is clearly a regression error, not an OS-incompatibility issue.

**Comment by crapo** [comment]
Regression error was on generation of the OWL files (in converting number to literal), not in inference. Fixed with commits to master.
