### ISSUE TITLE
SadlImplicitModel in tests

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#132]
The SadlImplicitModel is implicitly imported by any SADL model when running in the Eclipse IDE. However, in tests it is necessary to explicitly define and import the implicit model. Is there any way to make the import implicit in tests as well so that the models are the same? For an example see com.ge.research.sadl.tests, src/com.ge.research.sadl.tests.model.SadlModelProcessorTestTypeChecking.java.

**Comment by kittaakos** [comment]
I have created a PR to avoid explicit implicit model creation and import. Please note, the third test method is failing but it was the case before my changes.

PR is available at [here].

[here]: https://github.com/crapo/sadlos2/pull/133

**Comment by kittaakos** [comment]
Changes have been merged to master. I'm closing this issue.
