### ISSUE TITLE
Scoping problem with equations

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#136]
This doesn't make a lot of sense to me. Given these two models, the second importing the first:
 uri "http://sadl.org/eq.sadl" alias eq.
 External sum(decimal X, decimal X) returns decimal: "http://sadl.org/builtinfunctions#sum".

 uri "http://sadl.org/prop.sadl" alias prop.
 import "http://sadl.org/eq.sadl".
 Class1 is a class described by X with values of type float.

I get an error in the second model because "X" is scoped to be the variable "X" from the first model. This is incorrect because "X" in the first model should only be scoped to within the External (equation). I created a test case for this "testEquationScope" in com/ge/research/sadl/tests/model/SadlModelManagerProviderTest.xtend, which I've pushed to master. The test is currently ignored as it fails.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/138
Before merging PR, please look into the description. It would be great if we could prove the fix with two additional test cases. Thanks!

**Comment by kittaakos** [comment]
Fixes merged to master. Closing issue.
