### ISSUE TITLE
ValidationAcceptor passed into onGenerate

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#137]
The SadlModelProcessor onValidate method has a ValidationAcceptor passed in, allowing makers to be added easily while the onGenerate method does not. A ValidationAcceptor is needed in onGenerate because certain errors are detected during translation using the user-selected translator and these need to be reported via markers.

**Comment by kittaakos** [comment]
Short note on this task.

As we discussed a couple of weeks ago; these markers could be attached to the resource and shown to the user after saving the editor content. In other words, the user will not experience live validation while editing the file but only when the file content is already saved.

**Comment by crapo** [comment]
Would it be possible to display the markers at given locations after the save and translation? It would be considerably less useful to just have markers on the file but no information about where in the file the error relates to.

**Comment by kittaakos** [comment]
> Would it be possible to display the markers at given locations after the save and translation?

You mean adding an error marker to the model element in the editor?

It should be possible if we could clearly identify the violating `EObject` during the translation. If we have this problematic`EObject` instance, then we could gather its location from the `XtextResource`. From the location, we can get the line and column number. Once we have them, yes, we can create the marker with the position and reveal in the editor.

I hope, this answers your question.

**Comment by crapo** [comment]
Overcome by events--marker service now does what is needed.
