### ISSUE TITLE
Instance Declarations

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#14]
In OWLDeclarationsParserTest.xtend, I've added testInstanceDeclarations_01, .._02, and ..._03. _01 and _02 have situations not currently handled by the grammar. If covering these is not going to be disruptive it can certainly wait. Just mentioning it in case it might be disruptive and need to be addressed sooner rather than later....
_01: This is the case of blank (unnamed) instance nodes, aka bNodes. Once generation is implemented, the test statement should create an instance bNode of type Birth, an instance bNode of type Location, and the rest of the triples.
_02: In this instance declaration, the naming of the properties are such that the "has" connective is better left out. The ('has'|'with') should be optional in this construct.

**Comment by svenefftinge** [comment]
_01: anonymous instance nodes are supported in a nested context. I assumed that it wouldn'T make sense on top level as they couldn't be used anywhere. That is without a name nobody can ever reference them. Does that make sense?

_02: A quick test showed that this would introduce a lot of ambiguities. I could try to resolve them but it I understood working on the linking has higher priortity?

**Comment by crapo** [comment]
_01: Most of the things in the worlds that we model don't actually have unique identifiers, and it is a royal pain to try to give them such. Rather these things are identified by their relationship to other identified things, e.g., "A pen owned by Andy". (And even when they do have a unique identifier we often prefer to identify them by relationship, e.g.,  "The house where Sven lives". So, it is a very valid use case to have a top-level instance identified by the class and at least one relationship--the semantic validation can check for a disambiguating relationship.
_02: yes, lower priority than linking.

**Comment by svenefftinge** [comment]
I changed the test expectation for the _02 because the commas were causing problems.
