### ISSUE TITLE
Escape character not dropped on qualified names

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#144]
I guess this has been around for a long time and I just noticed it since none of the relevant code seems to have changed. If a keyword, e.g., "value", is escaped, e.g., "^value", everything works fine and by the time a call is made to QualifiedNameConverter.toQualifiedName the argument is "value". However, when it is in a qualified name, e.g., "otherns:^value", as is sometimes required, by the time the call to QualifiedNameConverter.toQualifiedName occurs the argument is "otherns:^value". I could remove the escape character here, but it seems unlikely to me that this is the right place to fix this and I don't know where it should be fixed...

I've added two tests:
1. QualifiedNameConverterTest, testConverter_02
2. SADLParsingTest, testQNameWithEscape (this test isn't complete and maybe it belongs elsewhere, but if it had the DeclarationExtentions inserted it would call getConcreteName(sr), which should return "value".

**Comment by kittaakos** [comment]
Above mentioned tests are available [here].

[here]: https://github.com/crapo/sadlos2/commit/939511cfd1cfbf3cdc07fcf243eb24c0ce35be4c

**Comment by crapo** [comment]
It appears that I made an incorrect assumption that a keyword, when used in a QName, must also be escaped as was the case in SADL2. It appears that one can write "otherns:value" and it will be parsed OK. Should it be OK to include an escape character? The SadlProperty created in the test for "LatticeToTree:value" has primaryDeclaration false, which is incorrect. The test should be, when determining where declaration is primary, if it is a QName and the prefix is not the alias of the current model.
