### ISSUE TITLE
ValueConverterService error on content assist

### ISSUE THREAD

**Issue by GEGlobalResearch** [crapo/sadlos2#145]
Given this model:

uri "http://sadl.org/ComponentLayer" alias ComponentLayer. 
COMPONENT_MANAGEMENT is a class.
COMPONENT1 is a class
    described by fault with a single value of type boolean
	described by channelA with a single value of type decimal,
	described by channelB with a single value of type decimal,
	described by min with a single value of type decimal,
	described by max with a single value of type decimal. 

Add a line "G is a COMPONENT1 with c"
then ask for content assist. In the resulting list, pick "COMPONENT1". The insertion into the line is such that it ends up being "G is a COMPONENT1 with com.ge.research.sadl.ValueConverterService$NameConverter@6f272319" 
(in master branch, not sure about others)

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/149

**Comment by kittaakos** [comment]
The fix has been merged; closing issue.
