### ISSUE TITLE
CopyQualifiedNameServiceTest.testCircle failing

### ISSUE THREAD

**Issue by GEGlobalResearch** [crapo/sadlos2#146]
selectedElement isn't a SadlResource so returns null

**Comment by kittaakos** [comment]
Could it be related to [this]? Simply the line endings are different on Windows and Unix, and that is a problem with the test. The problem should go away, once we merge the [SADL web prototype PR] to the master. Or the changes could be cherry-picked to master.

[this]: https://github.com/crapo/sadlos2/commit/d1a5d0fabf09405fdaceea168325712f6ffe88d1
[SADL web prototype PR]: https://github.com/crapo/sadlos2/pull/141

**Comment by kittaakos** [comment]
@crapo Does this still valid? At least on OSX, all qualified name copying tests are passing. Could you please verify on Windows as well. Thanks in advance!

**Comment by crapo** [comment]
This passes. Not sure when it stopped failing.
