### ISSUE TITLE
Instance Declaration

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#15]
In the instance declaration form on line 62 of SADL.xtext ({SadlInstance.type=current} instance+=SadlResource propertyInitializers+=SadlPropertyInitializer*), why is it "instance+=SadlResource"? I think that only one instance can be declared this way, although there may be any number of SadlPropertyInitializers following. This is also related to another issue--the instance name is optional, provided there is at least one SadlPropertyInitializer (which would be a validation check I think). Am I missing something?

**Comment by svenefftinge** [comment]
I fixed the += (made it =)
Regarding the optional name, I understood that anonymous instances are only valid in nested context, which is handled by the rule SadlNestedInstance.
Isn't that the case?
