### ISSUE TITLE
SadlImportProcessorProvider and associated need updating

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#154]
Changes in the way model processors and model processor providers work in going to Xtext 2.11 seem to not have bee applied correctly to SadlImportProcessorProvider and ISadlImportProcessor (with implementation in JenaBasedSadlImportProcessor). This is presumably a minor adjustment (for someone who understands what needs to be done :-)

**Comment by kittaakos** [comment]
I'll take care of it. Could you please provide a bare minimum example where we use the import processor, so I could write a headless and Eclipse-based test for it.

**Comment by crapo** [comment]
Take any simple OWL model, say one produced by a simple .sadl file. Import it using the importer and you should get a .sadl file from the .owl file that is semantically equivalent.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/155

**Comment by crapo** [comment]
Works very well. Thank you!
