### ISSUE TITLE
Re-enable self importing test case

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#158]
This [test] should be re-enabled: `SadlModelManagerProviderTest.testImportSelfError()`.

[test]: https://github.com/crapo/sadlos2/blob/master/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/model/SadlModelManagerProviderTest.xtend#L137

**Comment by kittaakos** [comment]
The test case is invalid. It supposed to test something else than it does currently.
The current test model has invalid import URI. It does not import itself.

```
uri "http://sadl.org/Tests/Import" alias imp.
import "http://sadl.org.Tests/ModelName".
```

should be replaced with this

```
uri "http://sadl.org/Tests/Import" alias imp.
import "http://sadl.org/Tests/Import".
```

**Comment by kittaakos** [comment]
If we would like to get rid of the Xtext linker error, we have to cover the case when a SADL model is importing itself. We have the correct validation in the SADL validator anyway. Something like this in the soft linking error message provider will do the trick:

```
class SoftLinkingMessageProvider extends LinkingDiagnosticMessageProvider {

	@Override
	override getUnresolvedProxyMessage(ILinkingDiagnosticContext it) {
		if (reference.EReferenceType === SADL_RESOURCE) {
			// treated as declaration. 
			return null
		} else if (reference === SADL_IMPORT__IMPORTED_RESOURCE && context instanceof SadlImport) {
			// Importing self causes linker error but that is handles already in SADL validator.
			val container = (context as SadlImport).eContainer;
			if (container instanceof SadlModel) {
				val baseUri = container.baseUri;
				if (baseUri == linkText) {
					return null;
				}
			}
		}
		return super.getUnresolvedProxyMessage(it);
	}

}
```

**Comment by kittaakos** [comment]
There is another issue; it is in the test assertion. We need to aggregate the issues from the resource validator and model processors instead of failing fast. Something like this:

```
	protected def Resource assertValidatesTo(CharSequence code, (OntModel, List<Issue>)=>void assertions) {
		val List<Issue> issues = newArrayList;
		val model = parser.parse(code);
		issues.addAll(validationTestHelper.validate(model));
		val processor = processorProvider.get;
		processor.onValidate(model.eResource, new ValidationAcceptor([issues += it]),  CheckMode.FAST_ONLY, new ProcessorContext(CancelIndicator.NullImpl,  preferenceProvider.getPreferenceValues(model.eResource)));
		assertions.apply(processor.theJenaModel, issues);
		return model.eResource;
	}
```

**Comment by kittaakos** [comment]
After applying all these changes we got the proper validation message from the SADL validator: `A model cannot import itself`. But we get two more issues from the model processor. The first one seems to be reasonable but the second one does not.

```
ERROR:Import of '__synthetic0.sadl' is part of a circular set of imports. (__synthetic0.sadl line : 2 column : 1)
ERROR: (__synthetic0.sadl line : 2 column : 1)
```

@crapo Could you please advise how to proceed with the second error? Unfortunately, I lack the domain knowledge.

**Comment by crapo** [comment]
I removed one message by checking for self-import in onValidate. The remaining 2 messages seem reasonable so I think this can be closed.

**Comment by kittaakos** [comment]
But the changes are not on the master. @crapo, do you want to keep it as closed?

**Comment by crapo** [comment]
I'm merging with master as soon as I figure out 1 more failing test.
