### ISSUE TITLE
How to use the issueAcceptor passed to JeanBasedSadlModelProcessor, onValidate

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#16]
When I detect an error generating the OWL model, how do I use the issueAcceptor, if that's the purpose, to return the issue?

**Comment by svenefftinge** [comment]
I will change the API to make it easier to add errors and warnings.

**Comment by svenefftinge** [comment]
Instead of an IAcceptor<Issue> a ValidationAcceptor is passed in that has addError and addWarning methods.
