### ISSUE TITLE
SadlImplicitModel.sadl content

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#162]
We need a way to generate the content for the SadlImplicitModel.sadl file in such a way that different content is provided based on the environment. There should be a version which supports Open Source SADL but it should be possible for derivative languages to provide a different version of this implicit model content.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/163

**Comment by kittaakos** [comment]
Closed via #163.
