### ISSUE TITLE
new method getOntConceptType(SadlResource) in DeclarationExtensions

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#17]
JenaBasedSadlModelProcessor needs to be able to get the basic ontology type of a SadlResource from the ResourceSet. The possible types are defined by this enum currently in JenaBasedSadlModelProcessor:

    enum OntConceptType {CLASS, OBJECTPROPERTY, DATATYPEPROPERTY, DATATYPE, ANNOTATION}

The method would be of the form:
    OntConceptType onttype =declarationExtensions.getOntConceptType(superSR);

**Comment by svenefftinge** [comment]
I added INSTANCE and renamed the two different properties to CLASS_PROPERTY and DATATYPE_PROPERTY. Also I did not yet delete the existing enum from JenaBasedSadlModelPRocessor as I didn't want to cause conflicts.

In case you find that the method doesn't return expected results, please add a test illustrating such cases to com.ge.research.sadl.tests.model.DeclarationExtensionsTest
