### ISSUE TITLE
Project-Specific Preferences Not Working Correctly

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#173]
Create a new project. Create a .sadl file with content:

 Person is a class described by age with values of type UnittedQuantity.

Save. Look at the .owl file in the OwlModels folder. If workspace preference Ignore UnittedQuantities... is checked, the range of age will be "decimal". If not it will be "UnittedQuantity". 

If workspace preference is not checked and project preference is, behavior is correct ("decimal").
If workspace preference is checked and project preference is not checked, behavior is *incorrect *("decimal").

**Comment by kittaakos** [comment]
First, I will write some test to be able to verify it as part of the build process.

**Comment by kittaakos** [comment]
It is a bug in Xtext. This bug exists a couple of years now. A related there can be found [here]. I have filed a corresponding bug in [xtext-eclipse].

[here]: https://www.eclipse.org/forums/index.php/m/1489371/
[xtext-eclipse]:  https://github.com/eclipse/xtext/issues/2399

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/174.
