### ISSUE TITLE
Need help fixing tests in GrammarContextIDsTest

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#176]
I've commented out the test in @AfterClass and added ignore for check_10, 11, 12. I don't know how to add the right component from the grammar to make the test correct.

**Comment by crapo** [comment]
Also 3 tests (2,3,4) in ui's SadlContentAssistTest are failing. The SadlModel is passed in as current model. Not sure what changed to make this start failing, but there is a valid statement in the model before the current invalid statement.

**Comment by kittaakos** [comment]
I will take care of this. As I can see, the changes are already on the master branch which simplifies the things.

> Also 3 tests (2,3,4) in ui's SadlContentAssistTest are failing. The SadlModel is passed in as current model. Not sure what changed to make this start failing, but there is a valid statement in the model before the current invalid statement.

I will open a separate issue for this. Otherwise, it will become hard to track the problems.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/180
