### ISSUE TITLE
SADL 3 Update Site

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#177]
It appears that there is an issue in the building of the SADL 3 update site. A user trying to install reported this error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: SADL Feature 3.1.0.201704191827 (com.ge.research.sadl.feature.feature.group 3.1.0.201704191827)
  Missing requirement: com.ge.research.sadl.ide 3.1.0.201704191827 (com.ge.research.sadl.ide 3.1.0.201704191827) requires 'bundle org.eclipse.lsp4j 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: SADL Feature 3.1.0.201704191827 (com.ge.research.sadl.feature.feature.group 3.1.0.201704191827)
    To: com.ge.research.sadl.ide [3.1.0.201704191827]

**Comment by kittaakos** [comment]
I will look into this issue. First, I try to reproduce it locally.

**Comment by kittaakos** [comment]
@crapo, could you please provide the necessary steps to be able to reproduce the problem locally? The maven build works fine from command line. It also works from Eclipse. The target platform is also valid in the development environment.

**Comment by kittaakos** [comment]
After downloading a new Eclipse IDE (`eclipse-java-neon-3-macosx-cocoa-x86_64.tar.gz`) and pointing to the `sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.update/com.ge.research.sadl.update-3.1.0-SNAPSHOT.zip` I have managed to reproduce the installation problem.

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: SADL Feature 3.1.0.201705031225 (com.ge.research.sadl.feature.feature.group 3.1.0.201705031225)
  Missing requirement: com.ge.research.sadl.ide 3.1.0.201705031225 (com.ge.research.sadl.ide 3.1.0.201705031225) requires 'bundle org.eclipse.lsp4j 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: SADL Feature 3.1.0.201705031225 (com.ge.research.sadl.feature.feature.group 3.1.0.201705031225)
    To: com.ge.research.sadl.ide [3.1.0.201705031225]
```

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/179
