### ISSUE TITLE
new method getUri(SadlResource) in DeclarationExtensions

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#18]
Given a SadlResource, JenaBasedSadlModelProcessor needs to be able to get the URI identifier of the resource. This might be done by adding a method to DeclarationExtensions of the form:

   String strSRUri = declarationExtensions.getUri(strSR);

or should it return a URI?

**Comment by svenefftinge** [comment]
The name getUri is a bit overloaded in the context of Xtext (see Resource.getUri). Could we use getOntUri instead?

**Comment by crapo** [comment]
Of course

**Comment by svenefftinge** [comment]
fixed in 5abf00d133f402c2f80276589d4c61995fe5fe9c
