### ISSUE TITLE
Adding External Resource mapping to ont-policy.rdf file via ConfigurationManagerForIDE

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#182]
ExternalEmfResource.xtend is used for external OWL resources. I added a load(Map<?,?> options) to override superclass method so that I could catch and display an exception from the load method. Not sure of best way to display--it is System.err.println right now.

I also need to get an instance of IConfigurationManagerForIDE so that I can add the mapping for this external OWL file to the ont-policy.rdf file. But to get a config mgr I need the OwlModels folder location and to do that I need the Project location. Is this load method the right place to be adding the mapping to the mapping file?

**Comment by crapo** [comment]
Sven suggested registering a generator for external resources. That sounded good, but I'm not sure exactly how to do that. A little nudge in the right direction would be greatly appreciated.

**Comment by kittaakos** [comment]
WIP PR: https://github.com/crapo/sadlos2/pull/195
