### ISSUE TITLE
MarkerService framework

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#183]
A Resource Listener for the error file will be implemented. We need to agree on the file extension.
1. when an error file changes or is created, it will be opened and the resource to which it applies and the marker type identified.
2. all markers of that type on that resource will be removed.
3. new markers will be created based on the content of the file.
The marker service is not specific to .sadl or .sreq or .sver. The error file identifies the URI of the resource to which the markers are to be added and they are added to that resouce
The translator does not need to provide the location. Given the name of a Rule or Requirement or Assumption or Assertion or Verify, the parser results (SadlModel) can be used to find the location of the statement with that name.
Since these are markers and not editor annotations, they will be created on saved resources and will not be created during editing.

**Comment by kittaakos** [comment]
TODOs:
- [ ] Document TP changes.

**Comment by kittaakos** [comment]
@crapo Do we have a single error XML file per Xtext resource or per project? Thanks!
For now, I go with the `err` file extension. We can change it later easily.

**Comment by crapo** [comment]
I believe that it will be per project, although I could foresee that some downstream processors could be per resource. If it works per project wouldn't it also then work per resource?

**Comment by kittaakos** [comment]
I just wanted to know which one you prefer. I implement the per project approach then.

**Comment by crapo** [comment]
Sure, but my question is that if a downstream process created a file per resource, the listener would pick them all up and it would still work, right?

**Comment by kittaakos** [comment]
Correct, that should work. But then both the project and the file specific files should have the same scheme.

**Comment by crapo** [comment]
Do you mean have the same XSD schema? I would agree. I think we should require that be the case.

**Comment by kittaakos** [comment]
@crapo, do we want to run the generator even if we have external SADL error markers attached to the Xtext resource?

Currently, which is the default Xtext behavior, the `EclipseBasedShouldGenerate` interrupts the generation if there are any error markers attached to the resource. We could customize it and run the generator even if there are any SADL external error markers on the saved resource.

Or do you want to run the external SADL marker generation in another phase? I thought it would be sufficient to run after save but before generation. What's your take on that?

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/188
