### ISSUE TITLE
Content assist with partial input

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#187]
In test below (Ignored in what is pushed to master):
	/** Completion after start of input */
	@Ignore
	@Test
	def void checkCA_25_DeclarationCompletion() {
		newBuilder(''' uri "http://sadl.org/classes.sadl" alias clses.
					   Shape is a class described by area with values of type float.
					   MyShape is a Sh''').assertProposal('Shape');
	}

I've already entered "Sh" and expect that when I ask for CA it will match those proposals that start with "Sh".

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/192
