### ISSUE TITLE
Show additional IMarker attributes in the RCP

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#191]
As a follow-up of #183, we would like to show somehow additional attributes attached to the `IMarker` instances in the problems view.

We could contribute a customized `Problems View` to the SADL perspective.

**Comment by crapo** [comment]
People are asking from hyperlinks in the marker text (editor marker popup and/or in the problems view) to specific locations in a file in the editor and to log or other output files. Is this possible?

Also, is there any reason why the error file (.err) couldn't have additional information causing an error or warning to be associated with a particular SadlResource within a named structure (e.g., Rule), which would allow that particular text to act as a popup on mouse over the the SadlResource (reference)?

**Comment by kittaakos** [comment]
Related to #252. I merge these things to there and close this task.
