### ISSUE TITLE
SADL 3 Update Site

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#193]
Now installation in a new Eclipse Standard Kepler SR2 produces this error:
Cannot complete the install because one or more required items could not be found.
  Software being installed: SADL Feature 3.1.0.201705051529 (com.ge.research.sadl.feature.feature.group 3.1.0.201705051529)
  Missing requirement: Xtext Testing Infrastructure 2.11.0.v20170124-1428 (org.eclipse.xtext.testing 2.11.0.v20170124-1428) requires 'bundle org.junit 4.12.0' but it could not be found
  Cannot satisfy dependency:
    From: SADL Feature 3.1.0.201705051529 (com.ge.research.sadl.feature.feature.group 3.1.0.201705051529)
    To: org.eclipse.xtext.testing [2.11.0.v20170124-1428]

**Comment by kittaakos** [comment]
Neither the built-in nor the SADL update site contains JUnit 4.12 by default. That should be added manually. So one need to do the following steps:
 - `Help` > `Install new Software...`.
 - Open the `Available Software Sites` from the hyperlink just below the text field.
 - Click on `Add...`.
 - Add the following `Location`: http://download.eclipse.org/tools/orbit/downloads/drops/R20150821153341/repository/ . The name can be empty, or one can choose any arbitrary name.
 - Close both dialogs with `OK.
 - Copy and past your SADL3 p2 update location and make sure that `Contact all update site during installation fo find required software` is checked in.

**Comment by kittaakos** [comment]
I am closing this issue as invalid. If we need to include JUnit 4.12 among the dependencies automatically, please open a separate Github ticket for that.

**Comment by crapo** [comment]
Akos,

I am a little puzzled. We’ve never run into this with ASSERT installation, so the update site for Requirements must include JUnit 4.12? Isn’t it a pretty simple thing to add it to the sadl parent target or some such thing?

Regards,
Andy

**Comment by kittaakos** [comment]
Reopened.

**Comment by kittaakos** [comment]
Verified with Kepler SR2:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: SADL Feature 3.1.0.201705290756 (com.ge.research.sadl.feature.feature.group 3.1.0.201705290756)
  Missing requirement: Xtext Testing Infrastructure 2.11.0.v20170124-1428 (org.eclipse.xtext.testing 2.11.0.v20170124-1428) requires 'bundle org.junit 4.12.0' but it could not be found
  Cannot satisfy dependency:
    From: SADL Feature 3.1.0.201705290756 (com.ge.research.sadl.feature.feature.group 3.1.0.201705290756)
    To: org.eclipse.xtext.testing [2.11.0.v20170124-1428]
```

**Comment by kittaakos** [comment]
The other SADL3 p2 update site related issue can be referenced here: #177.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/197
