### ISSUE TITLE
Content Assist with partial entry.

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#194]
SadlContentAssistTest.checCA_14c_PropertyInitializerValue_Positive still fails to provide "MyBar" as proposal and complete if selected.
uri "http://myUri". 
Bar is a class.
MyBar is a Bar.
Foo is a class described by p1 with values of type Bar. 
MyFoo is a Foo with p1 M

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/198
