### ISSUE TITLE
Relaxing statement order in SADL 3

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#20]
OWL is declarative and there are good reasons to relax, where possible, constraints on the order of statements in SADL. For example, consider these two statements:
		Person is a class described by owns with values of type Artifact.
		Artifact is a class.
When the first is processed we do not yet know whether Artifact is a Class or a Datatype, which is necessary to know whether "owns" is an owl:ObjectProperty or an owl:DatatypeProperty. 
As the JenaBasedSadlModelProcessor's onValidate method evolves toward a method for each sub-element of the statement which adds to the OWL model and returns created concepts for use in method of the calling the sub-element, I think I see a nice way to handle this and want to float it for comment. 
If a needed concept is not found in the model, e.g., "Artifact", throw a PendingErrorException which is populated with the sub-element not found, normally a SadlResource, as well as a message describing the possible error, e.g., "Artifact is not defined". At the SadlModelElement (statement) level, catch the exception, add the SadlModelElement being processed, and put it into a map of PendingErrorExceptions with the missing SadlResource as the key. This map can then be used to "re-submit" the SadlModelElement for processing later. This might be when the missing SadlResource is defined or at the end of statement processing. If the latter, some iteration might be necessary to try to do the pending errors in order as they may also have some dependencies.
Something like this is done in SADL 2, but I think this is simpler and more robust. Thoughts?

**Comment by svenefftinge** [comment]
Forward references are no issue, once I have implemented the linking. So I don't think you need to do anything about it, just ask for the type of Artifact.

**Comment by svenefftinge** [comment]
Closing this as of my previous comment. Please reopen if I have missed anything.
