### ISSUE TITLE
Extend SadlResource to be used as name of named structure

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#206]
Want to be able to name and reference grammar structures such as a query or a rule, or in extension language SRL a requirement.
[NamedQuery.zip](https://github.com/crapo/sadlos2/files/1103350/NamedQuery.zip)

**Comment by crapo** [comment]
Modified JenaBasedSadlModelProcessor method Query processStatement(QueryStatement element) to use SadlResource query name. This shows missing linking quite clearly as the declaration doesn't point to the other. I think this is set in SADLScopeProvider, but I'm a little fuzzy on exactly how it works.

**Comment by kittaakos** [comment]
The scoping related changes for the query statements: 9b0d215ff4b1d4bf2d5560587a5e650dbc868d2c

**Comment by kittaakos** [comment]
This was implemented and merged to master. I am closing this ticket.
