### ISSUE TITLE
List or Lists of values

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#21]
An option of SadlPropertyRestriction is:
    |   {SadlRangeRestriction} ('has'|'with') ('a' singleValued?='single' 'value'|('a' 'List'|'Lists') 'of' 'values'|'values') 'of' 'type' range=SadlPrimaryTypeReference

I don't think this me to tell whether "a List of values", "Lists of values", or "values" is present in the statement...

**Comment by crapo** [comment]
I think I have fixed this by adding a couple of flags in the SADL.xtext grammar--is this the best way to handle it?

**Comment by svenefftinge** [comment]
I understood these are all different syntactic forms to express singleValues (true or false).

**Comment by svenefftinge** [comment]
Fixed with d0f221c25367f60089008aad1131ca234d53f368
