### ISSUE TITLE
AbstractSadlTest should also load SadlBuiltinFunctions.sadl

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#217]
Similar to SadlImplicitModel, SadlBuiltinFunctions will need to be loaded by [yet to be written] test cases that use built-in functions.

**Comment by crapo** [comment]
This is now done, with one anomaly identified in #227

**Comment by kittaakos** [comment]
I have to reopen it. Currently, there are two separate ways we set the builtin function content. One is the model content provider you have introduced, the other is from the translator in `com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.createBuiltinFunctionImplicitModel(String)`.

Please decide which one is the truth. Right now, it is almost impossible to figure out what is going on when running tests and running the application. I have different validation results.

**Comment by kittaakos** [comment]
I will remove the built-in function content provider from the production code and move it to the tests. The built-in function content should come from the translator. Will be fixed as part of #226.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/234.
