### ISSUE TITLE
getOntConceptType of annotation property returns CLASS_PROPERTY

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#22]
Test case to reproduce: myAnnotationPropertyDeclarationCase in SadlModelManagerProviderTest.

**Comment by svenefftinge** [comment]
What should it return?

**Comment by crapo** [comment]
We could rename it ANNOTATION_PROPERTY, but ANNOTATION was what I expected. But yes, it is a property so a rename would make it more consistent.
