### ISSUE TITLE
DeclarationExtensions.getConcreteName returns qname

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#225]
Test case in com.ge.research.sadl.tests , com.ge.research.sadl.tests.model/DeclarationExtensionsTest.xtend, testGetConcreteName. Replace qname in lines per comment to make the test the one that now fails but should pass. Method getConceteName should not return the qualified name but only the local name. This seems to have been recently broken.

**Comment by kittaakos** [comment]
@crapo, with the proposed behavior changes we have three failing test cases. Please advise, which one should be then the correct behavior.

The following tests fail if I omit the prefix from the name:

  - <pre>com.ge.research.sadl.tests.model.SadlModelProcessorTestTypeChecking.testUserDefinedEquation()</pre>
  - <pre>com.ge.research.sadl.tests.model.SadlModelProcessorTestTypeChecking.testUndefinedEquation()</pre>
 - <pre>com.ge.research.sadl.tests.SADLParsingTest.testQNameWithEscape()</pre>

One can reference the corresponding change from [here](7dac69619c981f4750673b8f2420f3b6a3de3e07).

**Comment by crapo** [comment]
Only the 3rd test failure has anything to do with this change. I have fixed the 3rd test--it was clearly in error. 
The other two errors have to do with built-in functions. I'm looking into them.

**Comment by kittaakos** [comment]
Did you fix the test on a branch? It was not even broken without my changes on the master.

**Comment by crapo** [comment]
I hadn't pushed the 3rd test fix yet, but now I have.
The other test failures are because the SadlBuiltinFunctions model isn't being loaded automatically.

**Comment by crapo** [comment]
I thought I had done some work on to load the SadlBuiltinFunctionModel automatically in test cases. However, I don't find it now. That is the heart of the issue for the first two test case failures.

**Comment by crapo** [comment]
Importing of SadlBuiltinFunction.sadl model for tests working with one issue to discuss relative to the loading of the Resource and one test anomaly, see issue 226. The issue with getConcreteName is resolved.
