### ISSUE TITLE
Linking to imported concept with same local name

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#226]
If an ExternalEquation is defined with the same local name as an imported ExternalEquation, a reference in the current model links to the imported one unless the reference is a qname. This is the opposite of the desired behavior. See com.ge.research.sadl.tests.model.SadlModelProcessorTestTypeChecking, testUserDefinedEquation1 and testUserDefinedEquation2.

**Comment by crapo** [comment]
In today's discussion the new example was a bit out of the ordinary in that defining a concept with local name X in terms of an imported concept with local name X would be unusual. Much more usual is defining a new class or instance in this model when an imported model has a concept with the same local name.

**Comment by crapo** [comment]
I've added a test case testCrossResourceSadlResourceLinks_03 in SadlLinkingTest.xtend, a more appropriate place than in the model processor tests. It is ignored out as both the second and third asserts fail. I believe when linking works correctly this test will pass.

**Comment by kittaakos** [comment]
Unfortunately, the test case does not compile. I need to adjust it. I will declare it in the `SadlLinkingTest` on branch `GH-226`.

**Comment by crapo** [comment]
Akos, I can't send you email for some reason, but I've started a webex and am available to talk.

**Comment by crapo** [comment]
I did a little testing of SADL 2. 
If I have model A:
`uri "http://sadl.org/TestSadlIde/A" alias ModelA. 
Foo is a class.`
and I have model C:
`uri "http://sadl.org/TestSadlIde/C" alias ModelC.
import "http://sadl.org/TestSadlIde/A".
Foo is a class.`
I get the following warning on the last line of ModelC: 
"The class 'Foo' is already defined in imported model 'http://sadl.org/TestSadlIde/A#'
   and a new class is NOT being created. If you want to create
   a new class in this namespace, please use this model's prefix.

So the desired behavior would be:
1. If there is a "Foo" defined in one and only one imported model and someone references "Foo" it is a reference to the imported "Foo".
2. If there is a "Foo" defined in one and only one imported model and someone declares a class "Foo" in this model, warn that a new "Foo" is not being created, please use this model's prefix to create.
3. If a "Foo" is defined in two or more imported models and a reference is made to "Foo", the ambiguous name detection should detect and provide an error that a prefix must be used to identify which "Foo" is intended.
4. If a "Foo" is defined in two or more imported models and someone declares a class "Foo" in this model, it should be an error that there are multiple "Foo"s already and use a prefix if the intent is to create a new "Foo" in this model.

**Comment by kittaakos** [comment]
That is already very useful, but I could use some additional clarifications. Let's assume that the below four statements could be either true or false with the following model:
```
uri "http://sadl.org/Current.sadl" alias current.
import "http://sadl.org/I1.sadl" as i1.
import "http://sadl.org/I2.sadl" as i2.
```

 1. `current` model defines `Foo`.
 2. `current` model uses `Foo`.
 3. Either `i1` or `i2` defines `Foo`.
 4. Both `i1` and `i2` defines `Foo`.

```
     +---+---+---+---+
     | 1 | 2 | 3 | 4 |
+----+---+---+---+---+-----------------
| 00 | F | F | F | F | Nothing to do. Foo is neither defined nor used.
+----+---+---+---+---+-----------------
| 01 | F | F | F | T | Nothing to do. Although Foo is defined in both imported models, it is node used at all. No conflicts.
+----+---+---+---+---+-----------------
| 02 | F | F | T | F | Nothing to do. Same as use-case 01.
+----+---+---+---+---+-----------------
| 03 | F | F | T | T | Logically invalid. (Either-or cannot be both.)
+----+---+---+---+---+-----------------
| 04 | F | T | F | F | Error. The current model cannot use Foo if it is not defined at all.
+----+---+---+---+---+-----------------
| 05 | F | T | F | T | Foo cannot be used without the prefixes in the current model. Ambiguous error.
+----+---+---+---+---+-----------------
| 06 | F | T | T | F | Foo can be used in the current model without prefixes. It resolves to the imported one.
+----+---+---+---+---+-----------------
| 07 | F | T | T | T | Logically invalid. (Either or cannot be both.)
+----+---+---+---+---+-----------------
| 08 | T | F | F | F | Trivial. Nothing to do.
+----+---+---+---+---+-----------------
| 09 | T | F | F | T | ? Foo should be created with `current` prefix.
+----+---+---+---+---+-----------------
| 10 | T | F | T | F | ? Same as use-case 09: Foo should be created with `current` prefix.
+----+---+---+---+---+-----------------
| 11 | T | F | T | T | Logically invalid. (Either-or cannot be both.)
+----+---+---+---+---+-----------------
| 12 | T | T | F | F | Trivial. Nothing to do.
+----+---+---+---+---+-----------------
| 13 | T | T | F | T | ? Is it possible to reference Foo with prefixes? No, right?
+----+---+---+---+---+-----------------
| 14 | T | T | T | F | ? This seems to be use-case 14. Foo should be referenced with a prefix.
+----+---+---+---+---+-----------------
| 15 | T | T | T | T | Logically invalid. (Either-or cannot be both.)
+----+---+---+---+---+-----------------
```

Could you please verify the uses-case I have prefixed with the question-mark (`09`, `10`, `13` and `14`)?

> If there is a "Foo" defined in one and only one imported model and someone declares a class "Foo" in this model, warn that a new "Foo" is not being created, please use this model's prefix to create.

Raising a warning could be tricky here because we need to stop the generation on warnings. Can we go with an error here?

Do we need to apply the same rules in case of re-defining built-in functions? Built-in functions cannot be imported with an `alias` still those could be redefined.

Thank you in advance for the help!

**Comment by kittaakos** [comment]
I still believe that the ambiguous name validation is not enabled by default.
Are these issues related? #104 #230 
Also please see test case and advise: `SadlModelProcessorTestAmbiguousNames.testRequirement_ModelMinimal()`.

**Comment by kittaakos** [comment]
The ambiguous name detection is called only once from the `SadlSemanticHighlightingCalculator.provideHighlightingFor(XtextResource, IHighlightedPositionAcceptor, CancelIndicator)` per resource with `false`, so it seems to be disabled in production code.

**Comment by crapo** [comment]
Well, I tested both in test cases and in IDE last week and both were detecting. The default is false, but it is seems to actually get set to whatever is in the preferences. I changed preference setting and behavior changed correspondingly.

**Comment by kittaakos** [comment]
You're right. It is here: https://github.com/crapo/sadlos2/blob/c76e4dca83400d3965cc69e05b7a64fd68976ca6/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/syntaxcoloring/SadlSemanticHighlightingCalculator.xtend#L123

Thank you for the pointer to the preferences!

**Comment by crapo** [comment]
Sorry, didn't see the truth table comment earlier.
The warnings/errors don't necessarily need to be created in the Scoping code. The validation may be better able to detect. 
09: So "Foo is a class." should be scoped to the imported "Foo". The model processor/validator can give the warning.
10: ditto
13: Yes, this is OK with prefixes: "current:Foo is a class. MyFoo1 is a i1:Foo. MyFoo2 is an i2:Foo. MyFoo3 is current:Foo."
14: OK with prefixes: "current:Foo is a class. MyFoo1 is a i1:Foo. MyFoo3 is current:Foo."

**Comment by kittaakos** [comment]
Great, thanks!

**Comment by kittaakos** [comment]
> 09: So "Foo is a class." should be scoped to the imported "Foo". The model processor/validator can give the warning.

I do not understand this. As described in use-case 9, the current model imports `Foo` from both `I1` and `I2`.?

> 10: ditto

That is evident.

**Comment by crapo** [comment]
In both 09 and 10 there is only 1 import of a namespace containg "Foo". "Foo is a class." should be scoped to that single import. The model processor will check, when processing the statement, to see if "Foo" is an imported concept and create a warning marker.

**Comment by kittaakos** [comment]
Let assume we have the following model and the imported `I1` SADL model defines `Foo`.

```
uri "http://sadl.org/Current.sadl" alias current.
import "http://sadl.org/I1.sadl" as i1.

Foo is a class. // Line 4

Bar is a type of Foo. // Line 6
```

According to our discussion, we have agreed that we need to raise an ambiguous error in line 6 for `Foo` but nothing should be done with `Foo` in line 4. (Later we can add a warning here.) I did not yet find a good way to distinguish between the `Foo`s in line 4 and line 6. I think we need to mark both with an error unless you have a great idea how to ignore the first occurrence of `Foo` but mark the second one with an error.

I'm still trying to figure out something that fits our initial decision.

**Comment by crapo** [comment]
Marking both as error would be fine.

**Comment by kittaakos** [comment]
I have added more tests; interestingly, some tests fail in JUnit but work correctly in IDE. Something must be inconsistent between the IDE and the test setup. I need to look into the problem.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/234
