### ISSUE TITLE
Log output about expecting qualified names

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#228]
When the tests in SadlModelProcessorTestTypeChecking are run, I get these messages in the console window:
139195 [main] INFO  t.linking.impl.ImportedNamesAdapter  - getElements should be called with a QualifiedName during linking.
143876 [main] INFO  t.linking.impl.ImportedNamesAdapter  - getElements should be called with a QualifiedName during linking.
143876 [main] INFO  t.linking.impl.ImportedNamesAdapter  - getElements should be called with a QualifiedName during linking.
I suspect that that is because the list of names include qualified and unqualified names. Not sure how logging got turned on....

**Comment by kittaakos** [comment]
This can be ignored for now.
