### ISSUE TITLE
Verify that ambiguous name detection is working

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#230]
Don't know exactly how it is working, but it appears to. Test cases in SadlModelProcessorTestAmbiguousNames.xtend seem OK. Attached project detects ambiguous names in Names3.sadl, Names4.sadl, NamesB.sadl, Names.sreq, NamesB.sreq when enabled in preferences, doesn't detect when not enabled in preferences. Note that there seems to be some difficulty in detecting when imports are changed in editor.
[TestAmbiguousNames.zip](https://github.com/crapo/sadlos2/files/1249704/TestAmbiguousNames.zip)

**Comment by kittaakos** [comment]
It works iff the corresponding preference is enabled.
