### ISSUE TITLE
External Model Download 403

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#235]
When trying to download a model, e.g., from http://sadl.sourceforge.net/owl/apvf.owl, a connection 403 error occurs.

Investigation shows that the problem occurred for me because the proxy settings for GE Aviation were hard-coded into the method downloadURL in com.ge.research.sadl.externalmodels.editors.UrlListEditor.

What's the best way to allow proxies to be set? Properties file? System settings?

**Comment by kittaakos** [comment]
Exactly, I have checked the code too, and the current one is a dirty solution. I would go with preferences. Also, we should extract the logic from the UI.

**Comment by kittaakos** [comment]
We should retrieve the proxy settings from the preferences and set the system properties according to them.

**Comment by crapo** [comment]
When you say "extract the logic from the UI, do you mean the code to set the proxies from preferences? Where would you recommend?

**Comment by kittaakos** [comment]
Sorry for not being completely clear; I would move at least the entire `UrlListEditor.downloadURL(String, IPath, String)` method outside from the `MultiPageEditorPart` implementation. Getting the content from a URLConnection should not do much with the UI code.

**Comment by kittaakos** [comment]
The built-in Eclipse `Network Connections` preference page should be used for this.

**Comment by kittaakos** [comment]
@crapo, I have generalized the proxy setting a bit. The changes are here: eb9567e31521fbfac4a13a6a62638f8523499d2a.

It is important to note, that manual preference page configuration changes are required by the users if we would like to go with this generic solution.

 - One has to open preference page: `General` > `Network Connections`.
 - Set the active provider to `Manual` in the top-most drop-down.
 - And the configure the proxy settings manually.

<img width="702" alt="gh_235_proxy_settings" src="https://user-images.githubusercontent.com/1405703/30171678-eb5b3c08-93f2-11e7-8c2d-52c19d87962c.png">

Let me know if you need these changes and then I will create a PR.

**Comment by crapo** [comment]
@kittaakos , I'm looking for a reasonable place to put downloadURI. Does ResourceManager in com.ge.research.sadl.utils make sense? There aren't currently any classes in externalmodels that aren't UI, so I'm thinking another project?

**Comment by crapo** [comment]
@kittaakos , I think I still have the problem of converting the ExternaEmfResource's platform URI to a file URI in the getOrCreateSadlModel. Of maybe I can find the OwlModels folder and hence the project folder as platform URIs and open the policy file (in the OwlModels folder)? Right now the ConfigurationManager only works with file paths.

**Comment by kittaakos** [comment]
I do not really understand this questions here, probably wrong issue but you could use soemthing like this:
```
val path = org.eclipse.emf.common.util.URI.createPlatformPluginURI("projectName/some/path/to/resource", true).toPlatformString(true);
org.eclipse.core.resources.ResourcesPlugin.workspace.root.getFile(new org.eclipse.core.runtime.Path(path)).locationURI;
```

I have used the FQNs to make it clear without a context. I hope this helps.

**Comment by kittaakos** [comment]
If you have an EMF URI with `file` scheme, you can simply convert the string to a `java.net.URI` and then you have it.

**Comment by crapo** [comment]
I think the original intent of this issue, setting proxies, is solved.
