### ISSUE TITLE
It would be great to have a CI that runs the build each time one changes the master

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#236]
- a job for Windows,
 - and another one for OS X and/or Linux.

So we could see what was the breaking change when not all of the tests are passing.

**Comment by kittaakos** [comment]
We would like to use the free services from Travis-CI (*Nix builds) and Appveyor (Windows build).

**Comment by kittaakos** [comment]
PR: #240

**Comment by crapo** [comment]
Notification happens only when there is failure or when status goes from red to green.
