### ISSUE TITLE
Fix broken tests on master

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#237]
Currently, we have five broken test cases on the master branch.

<img width="638" alt="gh_237" src="https://user-images.githubusercontent.com/1405703/30111287-5e49970a-930d-11e7-945d-cd8c2c0e12f1.png">

**Comment by crapo** [comment]
I do not appear to have a class SadlExpressionParserTest. Is this the master branch?

**Comment by kittaakos** [comment]
Great catch, thanks for looking into it. It was a generated class in one of my `xtend-gen` folder. Which should not be there, but anyway, you are right. It does not exist on the master.

**Comment by crapo** [comment]
I've pushed a fix for the "testUserDefinedEquation<n>" failures to master.

**Comment by kittaakos** [comment]
> Correct?

Yes.

**Comment by crapo** [comment]
names changed, failing tests fixed
