### ISSUE TITLE
Tests are ignored in the maven build as their class name does not comply the default pattern from surefire

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#238]
AFAIK, the default pattern is *Test.java. Tests, such as `SadlModelProcessorTestCircularImports` and `SadlModelProcessorTestAmbiguousNames` are ignored. See the attached [full console log](https://github.com/crapo/sadlos2/files/1281048/sadl_mvn_full_console_log.txt).

**Comment by crapo** [comment]
Just glancing through tests, that would mean that an awful lot of tests are not being done in Maven builds. Would that include SadlLinkingTests.xtend? Sven created that one.

**Comment by kittaakos** [comment]
Just to make sure we are on the same page, all Xtend tests that end with *Test, run. Xtend files will result in Java test files.

I will do a quick grep and will see how many files are related.

**Comment by kittaakos** [comment]
I might have left out something but a quick grepping provided these files:
```
./src/com/ge/research/sadl/tests/model/SadlModelProcessorTestBasics
./src/com/ge/research/sadl/tests/model/SadlModelProcessorTestAmbiguousNames
./src/com/ge/research/sadl/tests/naming/GH_145_IncorrectValueConverterServiceOutput
./src/com/ge/research/sadl/tests/model/SadlModelProcessorTestCircularImports
./src/com/ge/research/sadl/tests/imports/GH_147_ImportScopeOnBrokenAST
./src/com/ge/research/sadl/tests/naming/GH_150_CannotCreateEObjectDescriptionWithBrokenAST
./src/com/ge/research/sadl/tests/model/SadlModelProcessorTestTypeChecking
./src/com/ge/research/sadl/tests/SadlLinkingTests
./src/com/ge/research/sadl/tests/GenerateTestCases
./src/com/ge/research/sadl/tests/markers/GH_216_ExternalMarkersDoesNotPreserveLFs
```

**Comment by crapo** [comment]
I have renamed tests and fixed those that were failing.

**Comment by crapo** [comment]
From [http://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html](url)
By default, the Surefire Plugin will automatically include all test classes with the following wildcard patterns:

"**/Test*.java" - includes all of its subdirectories and all Java filenames that start with "Test".
"**/*Test.java" - includes all of its subdirectories and all Java filenames that end with "Test".
"**/*Tests.java" - includes all of its subdirectories and all Java filenames that end with "Tests".
"**/*TestCase.java" - includes all of its subdirectories and all Java filenames that end with "TestCase".
