### ISSUE TITLE
Sadl Grammar changes?

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#243]
I've made some SADL grammar changes to extend functionality as requested by users. I'd like to review these with @svenefftinge.

Also there is a **significant** need for a grammar enhancement to allow the SADL 2 construct 
`<subject> <property> `
and not just 
`<subject> has <property>` in SubjHasProp expressions.

**Comment by crapo** [comment]
The grammar changes to be reviewed have to do with allowing length restrictions to be added to unnamed typed lists. They are in commit [https://github.com/crapo/sadlos2/commit/b605224d5e1e4106b8edc40ee9b4f93a14b60e97](url) on branch AATIM-2228. The kinds of models statements supported are tested by testListTypes_06 in SadlParsingTest.xtend. 
Note that I was not successful in supporting length in a declaration such as in testListTypes_07, which is currently ignored.

**Comment by crapo** [comment]
@svenefftinge , the test case for the desired grammar support of leaving out the "has/with" for "active" properties is testSubjectHasPropSomeMore added to SADLParsingTest and ignored.

**Comment by crapo** [comment]
Please note that any grammar changes should be made on a branch, not master, as there are many dependencies to be worked out for grammar changes.

**Comment by svenefftinge** [comment]
There are no tests called `testListTypes_07` or `testListTypes_06`. Could it be that you have not pushed them?

**Comment by crapo** [comment]
Just updated comment with correct names--sorry about that

**Comment by crapo** [comment]
On branch AATIM-2228, not master.

**Comment by svenefftinge** [comment]
I (surprisingly) found a way to solve it, which doesn't feel like a hack :). Let's see if this change works for your other scenarios as well.

**Comment by crapo** [comment]
Fantastic!! I have gathered together a model that has a number of constructs including a bunch of places where the 'has' should be optional. We can create a test case from this. I'm attaching the file for documentation purposes.
I created branch [GH-243](https://github.com/crapo/sadlos2/tree/GH-243) for this, but I had not yet created the branch when you added the commit. How can we apply this commit to this branch? I want to keep it separate from master for now.

**Comment by svenefftinge** [comment]
Could you just push to 'GH_243' instead (my branch)?

**Comment by crapo** [comment]
Oh, sure. I didn’t realize that you had created a branch. I was a little puzzled about how you could do a commit without it being to a particular branch, but I couldn’t see anything that told me what branch it was on.

**Comment by crapo** [comment]
Sven,

I added the best coverage I could come up with yesterday and it parses fine! The commas needed to go anyway.

I have a couple of grammar issues relating to unary operators on constants. Any reason to not just add the illustrative test case to this branch? I think they are easy fixes.

Thanks,
Andy

**Comment by crapo** [comment]
@svenefftinge , I've added 4 tests to SadlParsingTest.
1) testNegativeNumericConstants: does not pass (ignored in commit) because negation unary operator isn't working with numeric constants in two of the statements. I'm not sure why not.
2) testNegatedConstantsPropOfSubject: these all pass and express the same thing as the next test where certain statements fail
3) testNegatedConstantsSubjHasProp: here the numeric negation unary operator (-) works with constant but the logical negation unary operator (not) doesn't. I'm not sure why not. Test ignored in commit.
4) testInvalidUseOfConstants: verifies error condition when trying to do assignment with calculation.

**Comment by crapo** [comment]
In looking over the changes in tests, I think it will be wise to drop "... each of types " from the grammar. Here the "or" isn't really right as it's just a list, not a union. The construct has become misleading but to my knowledge no one ever used it anyway.

**Comment by crapo** [comment]
@svenefftinge , I need some help. I tried integrating the grammar change that introduced [UnitsExpression ](https://github.com/crapo/sadlos2/commit/c76e4dca83400d3965cc69e05b7a64fd68976ca6)with this grammar change to make has/with optional. I thought it was straight forward but I cannot make it work! Please help!!

**Comment by crapo** [comment]
@svenefftinge , the code discussed here is pushed to branch ExtendedIFT. While testing I made an additional change to the grammar to allow additional tests to pass: I changed line 333 so that "right=FeatureCall<EnabledWith>" rather than "right=UnitsExpression<EnabledWith>". This makes sense I think.
What surprised me is that the changes we make changed Name so that it is no longer a subclass of SadlResource. (Both are subclasses of Expression.) This caused many code changes just to be able to compile and will require many more to provide corrected model processing and get all tests to pass. Is this change in class structure of parse tree elements unavoidable? 

Also, the attempt to allow use of values like "-PI" was not very successful, with or without parentheses. Note that in declarations is makes sense to say that some value is "-PI" or "-e" but it doesn't make sense to say that the value is "not PI" or "known" or "not known". Therefore I think that "known" should be removed from SadlConstantLiteral on line 208. (I don't think SadlExplicitValue ever is used in Expressions?) However in Expressions such as Tests or conditions in a rule or a query, it does make sense to allow "known", "not known", "not PI", etc. See lines commented out in models in SADLParsingTest, testNegatedConstantsPropOfSubject and testNegatedConstantsSubjHasProp. Could you see if there is a fairly simple way to at least get the version with parentheses to work? 

Finally, the list length for unnamed typed lists works in the ways desired except for in declaration expressions. There is a test case in SADLParsingTest, testListTypes_04. The condition in the rule at line 143 is commented out. It would be nice to be able to check length restrictions as a condition perhaps. Do you see a not-too-far-reaching way to make that statement valid?
Thanks!

**Comment by svenefftinge** [comment]
To have Name extend SadlResource you need to extract the rule once more:
```
FeatureCall<EnabledWith> returns Expression:
	UnitsExpression<EnabledWith> |
	Name
;

Name return SadlResource: {
   {Name} name=[SadlResource|QNAME] ->(function?='(' arglist+=Expression? (',' arglist+=Expression)* ')')?
}
```

**Comment by svenefftinge** [comment]
Could you create another ticket for the -PI part maybe also a branch with the failing tests?

**Comment by crapo** [comment]
This is satisfactorily resolved in additional_grammar_changes branch
