### ISSUE TITLE
Put the build badges to the readme

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#244]
So that one can see the build status from the main GitHub page.

**Comment by kittaakos** [comment]
@crapo, I need some help getting the build-badge URL for Appveyoer.  One has to go to the [`sadlo2` project] at Appveyor, select settings from the top and finally, please select `Badges` from the left. I would need the content of the very last text area. That is the markdown format for the build-badge from the master branch. It should look like this:

```
[![Build status](https://ci.appveyor.com/api/projects/status/{someUniqueId}/branch/master?svg=true)](https://ci.appveyor.com/project/crapo/sadlos2/branch/master)
```

The one from Travis CI is this:
```
[![Build Status](https://travis-ci.org/crapo/sadlos2.svg?branch=master)](https://travis-ci.org/crapo/sadlos2)
```

[`sadlo2` project]: https://ci.appveyor.com/project/crapo/sadlos2/

**Comment by crapo** [comment]
`[![Build status](https://ci.appveyor.com/api/projects/status/293aewek023j2hom/branch/master?svg=true)](https://ci.appveyor.com/project/crapo/sadlos2/branch/master)`

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/261
