### ISSUE TITLE
JenaBasedRequirementsModelProcessor called for .sadl file in test

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#253]
Branch ExtendedIFT, sadlos2 and requirements repos. I changed the model processor in the com.ge.research.sadl.requirements.toprolog project, META_INF/services/com.ge.research.sadl.processing.IModelProcessor file from RequirementsToPrologModelProcessor to JenaBasedRequirementsModelProcessor. When I run the test case testUK in RequirementsModelProcessorTest, the onValidate method in the JenaBasedRequirementsModelProcessor is called for a .sadl resource. For now adding back in the test at the beginning of the onValidate method to return if not a .sreq resource, but should this be necessary?

**Comment by kittaakos** [comment]
No, we should have a one-to-one mapping. Long story short: we need to get rid of the `CompositeModelProcessor`.
