### ISSUE TITLE
Grammar problems with unary operators on constants

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#254]
sadlos2 branch ExtendedIFT;
@svenefftinge , the attempt to allow use of values like "-PI" was not very successful, with or without parentheses. Note that in declarations is makes sense to say that some value is "-PI" or "-e" but it doesn't make sense to say that the value is "not PI" or "known" or "not known"--those are not valid assignments. But, of course, it isn't a problem if they parse as they can be flagged as erroneous in validation. Therefore I think that "known" should be removed from SadlConstantLiteral on line 208. (I don't think SadlExplicitValue ever is used in Expressions?) However in Expressions such as Tests or conditions in a rule or a query, it does make sense to allow "known", "not known", "not PI", "not -e", etc. See lines commented out in models in SADLParsingTest, testNegatedConstantsPropOfSubject and testNegatedConstantsSubjHasProp. Could you see if there is a fairly simple way to at least get the version with parentheses to work?

**Comment by svenefftinge** [comment]
On that branch I have five test failures:
<img width="471" alt="screen shot 2017-10-02 at 14 38 09" src="https://user-images.githubusercontent.com/372735/31077597-5fa92486-a77f-11e7-866e-4d54bf3e2e66.png">

**Comment by crapo** [comment]
Ah, I see this branch doesn't have the renamed tests so a Maven build (at least on Windows) doesn't run these tests so I didn't know they were failing. I will fix.

**Comment by crapo** [comment]
I had added an info marker to assist with debug that was causing test failures in classes that were not run with Maven build. Renamed tests so they run for me, removed info marker. All tests now pass for me in this branch (ExtendedIFT).

**Comment by svenefftinge** [comment]
thank you, I am investigating different alternatives to restructure the grammar.

**Comment by crapo** [comment]
Resolved.
