### ISSUE TITLE
Units on expressions in "additional_grammar_changes"?

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#264]
@svenefftinge , @kittaakos, I have merged branch ExtendedIFT into the "additional_grammar_changes" branch and have done a little work to try to verify that the modified grammar covers all outstanding grammar requirements. I am a little confused about units on expressions. This was previously handled by the UnitsExpression. Tests of UnitsExpression were created for SRL but not for SADL. I have created a similar test in for SADL in SADLParsingTest, testUnitsOnExpressions. What confuses me is I only find "UNIT" on SadlNumberLiteral, as in the old grammar (master branch) but the new test passes. I'm not sure how it passes, or what the model processing code for units on expressions, if they are handled, might look like. I have done another snapshot update to "requirements" repo as well, "additional_grammar_changes" branch.

**Comment by crapo** [comment]
After looking at it a little more, I imagine that UnitsExpressions need to be reintroduced to the grammar, as they were in @svenefftinge 's commit https://github.com/crapo/sadlos2/commit/c76e4dca83400d3965cc69e05b7a64fd68976ca6. It's not entirely clear to me exactly how it interleaves with other expressions to get the desired precedence. In particular, I don't really understand that UnitsExpression was on the right of CommaSeparatedAbreviatedExpression and on the left of PropOfSubject. So an assist would be greatly appreciated.

**Comment by svenefftinge** [comment]
We cannot introduce `UnitsExpressions` again, since they conflict with `PropOfSubject`. You need to check instances of `PropOfSubject`whether they 'look' like a `UnitsExpression` and then treat it as such.

**Comment by kittaakos** [comment]
I have already adapted the tests for `Units` which does not exist anymore: https://github.com/crapo/sadlos2/commit/79ce8f612d9156e009ae0272d0bb875b1333b9b5#diff-30a9ab151d809b71fafddd0613d4cba4

**Comment by crapo** [comment]
@kittaakos , I have pushed changes, including one small grammar change, to the "additional_grammar_changes" branch. For me all tests pass during SADL maven build.

**Comment by crapo** [comment]
WRT the units expressions, a good test to put in place will be to take the testUnitsOnExpressions in SADLParsingTests.xtend and create a test with the same content in SadlModelProcessorBasicsTest.xtend that does the model processing of the units. I'm not suggesting this is the thing to do next, just that it will provide a means of working out model processing of units.

**Comment by kittaakos** [comment]
That is a great idea. I will try to create those tests. And thank you for resolving the rest of the failing issues.

**Comment by crapo** [comment]
Both <number> <unit> and SubjHasProp with null right as unit are now understood and working
