### ISSUE TITLE
Failure in SadlLinkingTest, additional_grammar_changes branch

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#267]
In testQueryVariable_1, there are failures in "weight" in Ask statments. Rather than "<weight>" as expected, it is returning "?weight?" because in the updateActual, "isDeclaration is set to "null".

**Comment by kittaakos** [comment]
The test case is failing due to this change: https://github.com/crapo/sadlos2/commit/023b2a577e3380ce02a986cf7c05ee415a04f937#diff-2bdfbb30e2798597f311426255f4a5ea.
Probably you know better, why was that necessary.

**Comment by crapo** [comment]
The change was made because a SubjHasProp does not always have a numeric left. In fact, the grammar changes were specifically to enable units on expressions. You have but to revert the two changed lines in SadlASTUtils to see examples in ExtendedIFTest: testU;nits_o9b, testUnits09c, testUnits_09, and testUnits_10 will then fail because the "unit" SadlResource, the SubjHasProp with null object, will be considered a variable as a property instead of a unit SadlResource.

**Comment by kittaakos** [comment]
OK, I will fix those then. The linking is disabled for SADL resources which stand for a unit. That's why the linking test failed.

**Comment by crapo** [comment]
That makes sense. I just sent you an email.

**Comment by kittaakos** [comment]
I have fixed it. Other units tests were passing too. Please note, after pulling your changes, I got an unrelated test failure: `com.ge.research.sadl.tests.model.SadlModelArticleTest.testArticles_03()`.

I am closing this.

**Comment by crapo** [comment]
My bad on the failing test. It is now fixed and pushed.
