### ISSUE TITLE
Where to do deep validation?

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#27]
Processing of a SadlModel can occur in JenaBasedSadlModelProcessor.onValidate, which appears to be called whenever a change is made in the editor, in JenaBasedSadlModelProcessor.onGenerate, which appears to be called when a file is saved or a build occurs, or in SADLValidator.xtend @Check methods. These appear to all be running in the same thread--when I set a break point in each, I do not get to the any other break point until I continue. When saving, first SADLValidate method is called, then onValidate, then onGenerate.

So, where to do "deep" semantic validation? In order to do "deep" semantic validation the actual OWL models will need to be loaded, doing transitive closure on imports. This is necessary because semantic validity depends on more than just the types of named concepts. It depends on set theory and first order logic considerations. 

The JenaBasedSadlModelProcessor.onValidate currently constructs the OWL model for a SADL file but does so naively--just accept whatever is input. My understanding is that this method should be kept as light-weight as possible. I thought that the SADLValidator was a thread separate from the UI thread and that I should do heavy lifting there, but am not seeing that. And if it is the place, perhaps it should just be at the SadlModel level so that I can build and transitively import a single time and do all checks?

I also note that on build, the call to onValidate is followed by a call to onGenerate, but the call is on two different instances of JenaBasedSadlModelProcessor, so I can't just write the OWL model to file in onGenerate that was created in onValidate...

**Comment by svenefftinge** [comment]
During onValidate you can freely navigate to the other resources and use the contents to create and enhance the Jena Model. I'm not sure if there is a way in Jena to link multiple OntModels together, such that we could have one per resource?

**Comment by crapo** [comment]
Not sure I understand the last sentence--question... An OWL model can import other models, which import others, as we have discussed. Jena, as a Java API to the OWL models, provides a way to find out about the imports, to actually import a model and all of its imports, etc. Don't understand the "one per resource" question--one what?

Also, I think you said deep validation can be in the onValidate method. Is that a different thread than the UI?

**Comment by svenefftinge** [comment]
Yes validation doesn't happen in the ui thread.

Am Dienstag, 17. November 2015 schrieb Andrew Crapo :

**Comment by svenefftinge** [comment]
Is this clarified? The IModelProcessor now even gets the CheckMode passed in, so we could skip expensive "deep" validation if the CheckMode doesn't include it.
