### ISSUE TITLE
difference in required parentheses between "element <n> of <list>" and "first element of <list>"

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#273]
Just want to ask the question about whether this parenthesizing is unavoidable. 
It is valid syntax to say "... if x is a Person and age of last element of children of x > 20" 
but it is a parser error to say "... if x is a Person and age of element 1 of children of x > 20"
(requires parentheses: "... if x is a Person and age of (element 1 of children of x) > 20").
Is this unavoidable? It's a subtlety that is not intuitive and the parser error "no viable alternative at input 'element'" isn't very suggestive... 
See test case ExtendedIFT testPrecedence_03 for example of what parsers and what doesn't.

**Comment by kittaakos** [comment]
Could you please advise on this, @svenefftinge? Thanks!

**Comment by svenefftinge** [comment]
Is it really `ExtendedIFT` I should look into? It doesn't seem to contain the latest grammar changes.

**Comment by kittaakos** [comment]
The branch is `additional_grammar_changes` and the test class name is `ExtendedIFTTest`.
[Here is](https://github.com/crapo/sadlos2/blob/c68afe3cd09befc4da6c2a63fce1c009f57f52f8/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/model/ExtendedIFTest.xtend#L565) the test case.

**Comment by svenefftinge** [comment]
Oh, thanks for clarifying. :)

**Comment by svenefftinge** [comment]
I pushed a new branch with grammar changes that would enable this. Note that the ElementInList would now no longer contain the subofprop, but the other way around. So any code that processes that needs to be adapted.

**Comment by crapo** [comment]
I believe this has resolved the issue and things are now working as expected.
