### ISSUE TITLE
UI Tests that check translator output and inference results

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#275]
The SADL UI tests create a temporary project folder where input files are created and output files are placed. Currently this temporary directory goes away but it could be used for two important testing purposes:
1) To test translator output. The translator is run when the model processor onGenerate is called so it is only a question of getting and testing that output before the temporary directory goes away. Examples of input and translator output need to be provided for this usage.
2) To test inference results. Here there would need be the ability to run the model inference processor, e.g., the JenaBasedSadInferenceProcessor, enable queries of the inferred model and then test the returned results against expected results. Examples need to be provided.

**Comment by crapo** [comment]
@kittaakos , here is a test case, a project with 3 files, attached as ZIP:
[Test.zip](https://github.com/crapo/sadlos2/files/1527388/Test.zip)
  Shapes.sadl, Polygons.sadl, Test.sadl.
The OwlModels folder should contain two rules files:
Shapes.rules:
# Jena Rules file generated by SADL IDE -- Do not edit! Edit the SADL model and regenerate.
#  Created from SADL model 'http://sadl.org/Shapes.sadl'

@prefix sadlimplicitmodel: <http://sadl.org/sadlimplicitmodel#>
@prefix GetInstance: <http://sadl.org/GetInstance.sadl#>
@prefix Shapes: <http://sadl.org/Shapes.sadl#>

[AreaOfCircle: (?c rdf:type http://sadl.org/Shapes.sadl#Circle), (?c http://sadl.org/Shapes.sadl#radius ?v0), pow(?v0, 2, ?v1), product(?v1, 3.141592653589793, ?v2) -> (?c http://sadl.org/Shapes.sadl#area ?v2)]

Polygons.rules:
# Jena Rules file generated by SADL IDE -- Do not edit! Edit the SADL model and regenerate.
#  Created from SADL model 'http://sadl.org/Polygons.sadl'

@prefix sadlimplicitmodel: <http://sadl.org/sadlimplicitmodel#>
@prefix GetInstance: <http://sadl.org/GetInstance.sadl#>
@prefix Precedence2: <http://sadl.org/Precedence2.sadl#>
@prefix rulevars: <http://sadl.org/rulevars.sadl#>
@prefix Shapes: <http://sadl.org/Shapes.sadl#>
@prefix ht: <http://sadl.org/HasTests.sadl#>
@prefix Polygons: <http://sadl.org/Polygons.sadl#>

[AreaOfRectangle: (?x rdf:type http://sadl.org/Polygons.sadl#Rectangle), (?x http://sadl.org/Polygons.sadl#height ?v0), (?x http://sadl.org/Polygons.sadl#width ?v1), product(?v0, ?v1, ?v2) -> (?x http://sadl.org/Shapes.sadl#area ?v2)]

The JenaBasedSadlModelInferenceProcessor is invoked to run inference. It has two methods of interest.

1. runInference--runs all of the commands in the .sadl file which is the Resource.
2. runNamedQuery--execute the specified query on the specified .sadl  or .owl Resource (other OWL formats to be supported)

Adhoc queries can be run against .sadl Resources or .owl Resources (other OWL formats need to be supported, TBD). Currently this is accomplished in the RunQuery execute method, which gets a ConfigurationManager for the containing project, gets a reasoner, translates the adhoc query, and then calls the reasoner to prepare the query (expand QNames into URIs). If the prepared query doesn't have any spaces or question marks, it is probably the name of a query rather than a query, so #2 above is called. Otherwise the actual query is passed to the reasoner "ask" method and the results are returned as a ResultSet. This should probably be encapsulated in a third method in JenaBasedSadlInferenceProcessor, runAdhocQuery?

Any of the queries in the project files could be adhoc query examples. The results of the queries you should be able to reproduce or I can supply the serialized results if desired. 

What else is needed?

**Comment by kittaakos** [comment]
@crapo, the `Shapes.sadl` file has a validation error, so it does not generate the corresponding rules file.
```
x, a variable of type  x, cannot be compared (is) with Rule, a class .
```
Can you please confirm that the input is correct? If so, what should I do to get rid of the errors? Thanks!

**Comment by kittaakos** [comment]
The generated rules file for the `Shapes.sadl` is the following after commenting out the line as mentioned earlier with the validation error:

```
# Jena Rules file generated by SADL IDE -- Do not edit! Edit the SADL model and regenerate.
#  Created from SADL model 'http://sadl.org/Shapes.sadl'

@prefix Shapes: <http://sadl.org/Shapes.sadl#>
@prefix Polygons: <http://sadl.org/Polygons.sadl#>

[AreaOfCircle: (?c rdf:type http://sadl.org/Shapes.sadl#Circle), (?c http://sadl.org/Shapes.sadl#radius ?v0), pow(?v0, 2, ?v1), product(?v1, 3.141592653589793, ?v2) -> (?c http://sadl.org/Shapes.sadl#area ?v2)]

```
 That is different than the expected output you have provided. Please advise.

**Comment by kittaakos** [comment]
Unfortunately, the API of the `ISadlInferenceProcessor` is not the most convenient. I can run the inferences for a resource, or run a named query, but the test code must deal with the `Object[]` return type.

**Comment by crapo** [comment]
Humm..., I'm missing somethiing. Here are the two rules, the one I provided and the one you provided:
[AreaOfCircle: (?c rdf:type http://sadl.org/Shapes.sadl#Circle), (?c http://sadl.org/Shapes.sadl#radius ?v0), pow(?v0, 2, ?v1), product(?v1, 3.141592653589793, ?v2) -> (?c http://sadl.org/Shapes.sadl#area ?v2)]
[AreaOfCircle: (?c rdf:type http://sadl.org/Shapes.sadl#Circle), (?c http://sadl.org/Shapes.sadl#radius ?v0), pow(?v0, 2, ?v1), product(?v1, 3.141592653589793, ?v2) -> (?c http://sadl.org/Shapes.sadl#area ?v2)]

**Comment by kittaakos** [comment]
I have noticed, something is inconsistent with the generated rules. Sometimes, I get the following output:
```
# Jena Rules file generated by SADL IDE -- Do not edit! Edit the SADL model and regenerate.
#  Created from SADL model 'http://sadl.org/Shapes.sadl'

@prefix Shapes: <http://sadl.org/Shapes.sadl#>
@prefix Polygons: <http://sadl.org/Polygons.sadl#>

[AreaOfCircle: (?c rdf:type http://sadl.org/Shapes.sadl#Circle), (?c http://sadl.org/Shapes.sadl#radius ?v0), pow(?v0, 2, ?v1), product(?v1, 3.141592653589793, ?v2) -> (?c http://sadl.org/Shapes.sadl#area ?v2)]

```

Sometimes the `polygons` prefix is missing:
```
# Jena Rules file generated by SADL IDE -- Do not edit! Edit the SADL model and regenerate.
#  Created from SADL model 'http://sadl.org/Shapes.sadl'

@prefix Shapes: <http://sadl.org/Shapes.sadl#>

[AreaOfCircle: (?c rdf:type http://sadl.org/Shapes.sadl#Circle), (?c http://sadl.org/Shapes.sadl#radius ?v0), pow(?v0, 2, ?v1), product(?v1, 3.141592653589793, ?v2) -> (?c http://sadl.org/Shapes.sadl#area ?v2)]

```

**Comment by kittaakos** [comment]
> Here are the two rules, the one I provided and the one you provided:

The output you have provided has the implicit model prefix; mine does not have it.

**Comment by crapo** [comment]
Ah, I see. The prefixes aren't used so make no difference. But I had missed the inconsistency.

**Comment by crapo** [comment]
What branch are you working? I do not have a validation error on the query "Ask: x is a ^Rule." I assume that is where you saw the validation error?

**Comment by kittaakos** [comment]
I am working on GH-275.

Unfortunately, the `Test.sadl` file has the same error in `Ask: x is a ^Rule.`.

**Comment by kittaakos** [comment]
> The prefixes aren't used so make no difference.

I cannot compare the content if it is not consistent and changes all the time.

**Comment by crapo** [comment]
Yes, this will be resolved. I meant what code branch? I do not think the development branch will generate these errors on the query.

**Comment by kittaakos** [comment]
> I meant what code branch?

As I said, I work on `GH-275` branch. See here: https://github.com/crapo/sadlos2/tree/GH-275.

**Comment by crapo** [comment]
The problem was that the prefixes map wasn't being cleared so it had whatever was left over from rule files previously created. I've fixed this in development branch. It appears that GH-275 is branched from master?
 My fixes are in development which is a major divergence from master.

**Comment by kittaakos** [comment]
OK, I will move the changes to a new branch. Thank you for the quick fix!

**Comment by kittaakos** [comment]
> I've fixed this in development branch.

Did you push your changes? My tests are still failing although I have moved my modifications to a new branch which I have created from the `development`?

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/281

**Comment by kittaakos** [comment]
@crapo, I have created a PR with the initial implementation, please review.
