### ISSUE TITLE
Configure the Xtext bindings to support customized hover for SADL resources

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#276]
If a SADL resource has additional RDF comments attached to it, show that in the pop-up when hovering over the AST node element in the editor.

This task is not intended to provide the actual RDF comment implementation, it is just about setting up Xtext to support that in SADL.

**Comment by kittaakos** [comment]
PR with the bare-minimum changes are here: https://github.com/crapo/sadlos2/pull/277.

This will look like this:

<img width="627" alt="gh-276" src="https://user-images.githubusercontent.com/1405703/33444927-d62a57e2-d5fb-11e7-8fb3-a7cf245a7c5a.png">

**Comment by nbachman** [comment]
@kittaakos Can you confirm that this story is ready to be closed? I see that #277 which has the conspicuous title of "DO NOT MERGE" is ready to be merged.

**Comment by kittaakos** [comment]
@nbachman, this task was just a discovery task. We had to check whether it is possible to show RDF comments in the pop-up dialog. If yes, how difficult it is to implement.

> This task is not intended to provide the actual RDF comment implementation, it is just about setting up Xtext to support that in SADL.

It is possible to implement this feature, and it should be straightforward. I would propose to close this task and the PR **too** without merging it but please keep the branch alive.
