### ISSUE TITLE
Help implementing a Java function isContainedBy(EObject eobj, ?)

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#280]
@kittaakos , I have a method in JenaBasedSadlModelProcessor called isContainedBy. The intent is that I can ask if a particular EObject is contained by a particular parse tree class, e.g., is thie EObject contained by a QueryStatement? However, it doesn't really work, except for QueryStatement and then only because that is hardwired in the method. What am I doing wrong? I know you have a method like this in the Xtend code...

**Comment by kittaakos** [comment]
I am not sure if you are talking about this or not:

```java
EcoreUtil2.getContainerOfType(obj, QueryStatement.class) != null
```

If no, maybe you can provide one or two test cases, and I'll check that.

**Comment by kittaakos** [comment]
Did it help? I [can see](https://github.com/crapo/sadlos2/commit/b514523daf6ca94719142ac52fb9f0a3706af0c4), you are using it.

**Comment by crapo** [comment]
Yes, it works. I was trying to encapsulate it in a method, but I got rid of that approach. Thanks!!
