### ISSUE TITLE
Make "then" optional in rules?

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#284]
Current SADL rule grammar is:
`RuleStatement returns ExpressionScope :
	{RuleStatement}
	'Rule' name=SadlResource (annotations+=NamedStructureAnnotation)* ':'? 
                ('given' ifs+=Expression)? 
                ('if' ifs+=Expression)?
		'then' thens +=Expression
;`

How would one change this grammar to have the same Rule syntax, but to allow 'then" to be optional if and only if there were no 'given' or 'if' Expressions?
(Note: the parts have += because they used to allow comma-separated expressions)

**Comment by kittaakos** [comment]
@crapo, I am a bit confused, did you mean this:

> if and only if there were no 'given' or 'if' Expressions

there were no `given`s AND  no `if`s.

If no, could you please add 3-4 parser tests or short SADL snippets to this issue? Thank you!

**Comment by crapo** [comment]
My carelessness. Yes, I mean if and only if there are no 'given' and no 'if' Expressions

**Comment by kittaakos** [comment]
@crapo, if you are happy with the approach I have suggested, then you will find the PR with the changes (against the `development`) branch [here](https://github.com/crapo/sadlos2/pull/285).

**Comment by crapo** [comment]
Yes, that is a great solution! I was thinking only of the grammar so I missed this entirely.

**Comment by crapo** [comment]
Actually, now I see I wasn't reviewing carefully enough. The desire was not to have the entire then segment of the rule optional, but to make the 'then' keyword optional if and only if there are no rule conditions ('given' AND 'if' both not present in rule, e.g., 
Rule AreaOfCircle: area is PI*radius^2.

**Comment by kittaakos** [comment]
We cannot make this change without breaking something.

There are two possible ways to support it.
 1.  We have to make the colon mandatory after the rule name and the annotations (if any):

```
Rule R: // OK
  given
    p is a Person
  if 
    p is a Person and p has age > 30
  then
    print("hi").
```

```
Rule R // ERROR
  given
    p is a Person
  if 
    p is a Person and p has age > 30
  then
    print("hi").
```

 2. We leave it as it was but make it mandatory if there are no `givens` and no `if`s:

```
Rule R: // OK
  given
    p is a Person
  if 
    p is a Person and p has age > 30
  then
    print("hi").
```

```
Rule R // OK
  given
    p is a Person
  if 
    p is a Person and p has age > 30
  then
    print("hi").
```

```
Rule R: // OK
    print("hi").
```

```
Rule R // ERROR
    print("hi").
```

```
Rule R: // OK
    then
      print("hi").
```

```
Rule R // ERROR
    then
      print("hi").
```

**Comment by crapo** [comment]
I suspect the best solution is to not change it. Thanks for looking into the question.

**Comment by kittaakos** [comment]
Could you please revert the changes from the `development` branch?

**Comment by crapo** [comment]
I reverted the grammar and SadlValidator check but just modified the tests as they seemed useful.

**Comment by kittaakos** [comment]
Thank you!
