### ISSUE TITLE
Configure the Xtext bindings to support customized hover for SADL resources - Implementation

### ISSUE THREAD

**Issue by nbachman** [crapo/sadlos2#286]
From [GH-276](https://github.com/crapo/sadlos2/issues/276): "If a SADL resource has additional RDF comments attached to it, show that in the pop-up when hovering over the AST node element in the editor."

This issue was created to implement the functionality mentioned in the previous issue.

**Comment by kittaakos** [comment]
For the actual implementation, I would need the desired output format. Also, a way to get the RDF comments (if any) for a particular SADL resource. Do we already have such a utility/service method?

**Comment by nbachman** [comment]
As it currently stands, if a comment is placed before the initial declaration of any element, a tooltip will appear for every instance of that element with the comment text. Our users indicated this would be sufficient. 

I will close this issue now.

**Comment by nbachman** [comment]
As per our discussion with @crapo today, we would like to utilize the "note" functionality of the grammar to populate the tooltips. This will allow the comment to be part of the OWL model and far more accessible. 

![image](https://user-images.githubusercontent.com/3697739/37467309-3f633f62-2836-11e8-9611-ad292bbd62d6.png)

![image](https://user-images.githubusercontent.com/3697739/37467344-533430fa-2836-11e8-88e2-fc3998c47070.png)

![image](https://user-images.githubusercontent.com/3697739/37467424-903b3688-2836-11e8-93e8-6c217f55b100.png)

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/287.

Please review.

**Comment by kittaakos** [comment]
![gh-286](https://user-images.githubusercontent.com/1405703/37591738-bca2584e-2b6c-11e8-8603-5540deb7c656.gif)

**Comment by crapo** [comment]
Looks good to me. Forwarded these to Nick, who is working the related Jira.
The animated gif is cool!! You'll have to tell us how you did that.

**Comment by nbachman** [comment]
The implementation looks good. The functionality works as intended. All tests pass.
