### ISSUE TITLE
Output Configuration for IFileSystemAccess2

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#29]
In the JenaBasedSadlModelProcessor's onGenerate method, there is an argument of type IFileSystemAccess2 passed in, which can be used to generate the OWL file. By default this goes into the default configuration's "src-gen" folder. It seems that a different output configuration could be generated that would put the generated file in the "OwlModels" folder, but I can't seem to find documentation on how to set/use a custom output configuration...

**Comment by svenefftinge** [comment]
In eclipse you can change the output folder in the preferences.
In addition we can set the default differently by subclassing and binding org.eclipse.xtext.generator.OutputConfigurationProvider

**Comment by crapo** [comment]
This link seems relevant to the latter solution: http://www.programcreek.com/java-api-examples/index.php?api=org.eclipse.xtext.generator.IFileSystemAccess
