### ISSUE TITLE
Project-specific preferences not working in JenaBasedSadlInferenceProcessor

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#290]
The com.ge.research.sadl.ui class RunInference, execute method, calls getPreferences() in its superclass, SadlActionHandler. This creates a map of preferences for inference-related preference settings, e.g., Sadlpreferences.SHOW_TIMING_INFORMATION. The project-specific setting is not correctly retrieved while the workspace setting is.

To reproduce, use any project with a test or query or even a Print: statement (SadlCommand). The Shapes Demo will do. Set the preference for show timing to true for the project. The map will have false. Set true for workspace and the correct value will be retrieved.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/291
