### ISSUE TITLE
Uniqueness of model uris and aliases

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#30]
Do I need to add a specific check to make sure that a model uri and a model uri alias are not used by another resource in the resource set to the SADLValidator? It appears that currently no error is generated by duplication in either or both.

**Comment by svenefftinge** [comment]
Yes, we need to add a validation for that.

**Comment by crapo** [comment]
I've added a test (second one) in SadlModelManagerProviderTest.xtend. I tried to fashion this after the linking tests, where you parse two models and the second imports the first, only here the second duplicates the URI of the first and I want to make sure it is caught as an error. However, the first model doesn't seem to be in the ResourceSet when the second is parsed. Can you give me an assist please?
