### ISSUE TITLE
[windows] Failing UI tests on the `development` branch

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#317]
As of the [`HEAD`](https://github.com/crapo/sadlos2/commit/06d412e2bb195292f861251d5b43cef2a0409455) of the `development` branch, I have failing UI tests on Windows. This does not happen on OS X. Although this is just a wild guess, some process or stream still uses the test model files and the test workspace cannot be cleaned up.

<img width="465" alt="screen shot 2018-05-23 at 13 15 40" src="https://user-images.githubusercontent.com/1405703/40421314-c8e8350e-5e8b-11e8-8338-dfa84c0364b9.png">

**Comment by kittaakos** [comment]
```
Status ERROR: org.eclipse.core.resources code=273 Problems encountered while deleting resources. null children=[[type: ERROR], [path: /GH_275_CheckTranslatorAndInferencerPluginTest_checkTranslatorOutput/OwlModels], [message: Could not delete '/GH_275_CheckTranslatorAndInferencerPluginTest_checkTranslatorOutput/OwlModels'.], [plugin: org.eclipse.core.resources], [exception: org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.]
 [type: ERROR], [path: /GH_275_CheckTranslatorAndInferencerPluginTest_checkTranslatorOutput], [message: Could not delete 'C:\Users\kittaakos\dev\eclipse-wss\junit-workspace\GH_275_CheckTranslatorAndInferencerPluginTest_checkTranslatorOutput'.], [plugin: org.eclipse.core.resources], [exception: null]
]
```

**Comment by kittaakos** [comment]
The `rules` files seem to remain there after the deletion.
```
05/23/2018  01:50 PM    <DIR>          .
05/23/2018  01:50 PM    <DIR>          ..
05/23/2018  01:50 PM               486 Polygons.rules
05/23/2018  01:50 PM               409 Shapes.rules
               2 File(s)            895 bytes
               2 Dir(s)  29,448,429,568 bytes free
```

**Comment by kittaakos** [comment]
I have tried to unset the read-only flag before the deletion. It did not work. Also, I have tried to create the rules files with `readonly` `false` flag, that did not work either. I would say, some process keeps the file open and that's the reason Windows does not allow deleting it.

**Comment by kittaakos** [comment]
I got this when I ran the `com.ge.research.sadl.ui.test.inference.GH_275_CheckTranslatorAndInferencerPluginTest.checkTranslatorOutput()` test. I had the problem on my Windows 10 image, also on the Windows CI. The test is green on OS X.

**Comment by crapo** [comment]
I do not get any errors running that test, development branch.

**Comment by kittaakos** [comment]
Thanks for checking! I will try to reproduce it again on my Windows image.

**Comment by kittaakos** [comment]
It does not happen on AppVeyor anymore. I am closing this. Please reopen if you see the same test failures.
