### ISSUE TITLE
[T] Broken tests in `c.g.r.sadl.jena-wrapper-for-sadl`

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#332]
I cannot run the tests. Same failure when working on #296. I will disable them. This GH issue is for fixing and enabling the tests.

![screen shot 2018-09-25 at 14 15 45](https://user-images.githubusercontent.com/1405703/46013879-cb832b80-c0cd-11e8-8bf2-dad2cc8eba36.jpg)

**Comment by crapo** [comment]
which model to use was incorrect. fixed.
