### ISSUE TITLE
External OWL models from file URL?

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#336]
When I edited an externalmodels.url and put in a file:/... URL, it failed with an error message about not being a platform URL. This was working. Maybe it got broken in the Web SADL work?

**Comment by kittaakos** [comment]
> Maybe it got broken in the Web SADL work?

Yes. I was not aware of this feature. I will take care of it.

**Comment by crapo** [comment]
Humm... Now I'm seeing an error for http URIs. 

Create a new project, create a .sadl file to give it the correct nature.
Add this content to an externalmodels.url file:

--This is a list of URLs of OWL model files to add to the external models directory for this project.
http://sadl.sourceforge.net/owl/apvf.owl
http://sadl.sourceforge.net/owl/aulo.owl
http://sadl.sourceforge.net/owl/time-entry.owl

In UrlListEditor.sdownloadModels line 231, modelDefinitionUri is
   file:/D:/Users/200005201/aske-workspace/TA1/ModelsFromCode/Ontologies/externalmodels.url
This is passed into the call to ExternalEmfModelDownloader.downloadModels. At line 81 the call to EclipseSadlProjectHelper.getRoot results in a call to checkUri for the URI passed in, resulting in a an IllegalArgumentException from call at line 74, "Expected a platform:/resource/ URI..."

Stack trace:
`java.lang.IllegalArgumentException: Expected a `platform:/resource/` URI. Got instead: file:/D:/Users/200005201/aske-workspace/TA1/ModelsFromCode/Ontologies/externalmodels.url.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
	at com.ge.research.sadl.ui.utils.EclipseSadlProjectHelper.checkUri(EclipseSadlProjectHelper.java:129)
	at com.ge.research.sadl.ui.utils.EclipseSadlProjectHelper.getRoot(EclipseSadlProjectHelper.java:61)
	at com.ge.research.sadl.external.ExternalEmfModelDownloader.downloadModels(ExternalEmfModelDownloader.java:81)
	at com.ge.research.sadl.externalmodels.editors.UrlListEditor.downloadModels(UrlListEditor.java:231)`

**Comment by kittaakos** [comment]
I have fixed the download logic for both the `http` and the `file` URIs.

PR: https://github.com/crapo/sadlos2/pull/343

**Comment by crapo** [comment]
Now it appears to work correctly. Thanks!
