### ISSUE TITLE
External models in Web SADL

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#337]
This is probably a documentation question. My understanding is that Web SADL supports external models. I don't see it in the list of "Known Limitations". So I create an OWL file somewhere on the drive, say at "/DATA/externals/MyFile.owl" and add "file:/DATA/externals/MyFile.owl" to my.url file. How do I then cause the action equivalent of clicking on "Download External Models" to occur?

**Comment by kittaakos** [comment]
It is the same as https://github.com/crapo/sadlos2/issues/336.

It does not handle URIs with the `file` scheme. I am closing this.
