### ISSUE TITLE
Need to have process to build updated docker image for Web SADL

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#339]

**Comment by kittaakos** [comment]
@crapo, do you have any preferences on this issue?
 - What service should we use? (Travis CI, AppVeyor, Azure, etc...)
 - Who should be the administrator of the services? (We have to generate, encrypt, and use GitHub and npmjs.org OAuth tokens on the CIs.)
 - When do you want to build a new language server?
 - When should we publish the Theia SADL extension
 - When do we want to build the new Docker image?

**Comment by crapo** [comment]
@kittaakos , I have created all the tokens, etc., per your instructions in email. Ready for next step as far as I know.
