### ISSUE TITLE
SadlBaseModel processing?

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#340]
The SadlBaseModel.owl file in the OwlModels folder is imported explicitly into every OWL model created from a .sadl file. However, the concepts defined in the SadlBaseModel.owl are not available in the .sadl file. What would be involved in making the SadlBaseModel.owl file an impllicit import in the .sadl files as well so that, for example, I could create a .sadl file containing:

 uri "http://sadl.org/Exploratory.sadl" alias explore.
  BBN is a type of ^Equation.

Just wondering....

**Comment by crapo** [comment]
This is probably related to Issue #248

**Comment by kittaakos** [comment]
> What would be involved in making the SadlBaseModel.owl file an impllicit import in the .sadl files

We need to adjust the scoping and the `ExternalEmfResource` with the factories and the predicates. I cannot see any technical obstacles, but this requires further investigation and a bunch of test cases.

**Comment by kittaakos** [comment]
I am not sure we can keep the `SadlBaseModel.owl` file in the `OwlModels` folder. The `OwlModels` folder is the gen folder and we [use the generator to create it](https://github.com/crapo/sadlos2/blob/847f26c7b5efb5b3ca4da0528824776524350eff/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L521). It will be a derived resource, so it will be deleted and re-created by the builder. For the implicit model and the built-in functions, we do [**not** use the generator](https://github.com/crapo/sadlos2/blob/847f26c7b5efb5b3ca4da0528824776524350eff/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L11137). Can I change the generation lifecycle and the target folder from `OwlModel` to `ImplicitModels`?

**Comment by GEGlobalResearch** [comment]
I think that would be fine, as long as that doesn't break the auto-importing into every model in the project. That leaves a couple of other OWL files that are automatically generated and put in the OwlModels folder that we do not want to index, but that should be fine I think--the ones in the ImplicitModel folder are indexed and the auto-generated in the OwlModels folder are not indexed.

**Comment by kittaakos** [comment]
If we have to change the current implementation and the location of the `SadlBaseModel.owl` from `OwlModels` to `ImplicitModels` anyway, would it be possible to have a `SadlBaseModel.sadl` file instead and the generator would take care of generation. With this approach:
 - we do not have to customize the external EMF resource logic,
 - we would handle the built-in functions, the implicit model, and the base model the same way.

What do you think?

**Comment by kittaakos** [comment]
> Well, at that point I'm not sure there is any reason to have both the SadlBaseModel and the SadlImplicitModel. Maybe the best solution is to get rid of the SadlBaseModel and move the things I want indexed to the implicit model.

👍

> I guess going this route means nothing needs to happen other than I move some content. I like that!

Is there anything I need to do with this task?

**Comment by GEGlobalResearch** [comment]
No, I think you've brought it to a successful conclusion. Ball is now in my court. Thanks!
