### ISSUE TITLE
"." (dot) is legal in concept names

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#35]
Grammar: “.” (dot) is the end-of-statement character but is also legal as i) in a URI local fragment (resource name) and ii) as a decimal point in a number. Currently using it as a character in a concept name creates an error. Also, ending a line with a number followed by “.” without a space before the dot generates an error. In previous versions of the grammar if the ending dot was followed by white space or EOF it was recognized as the EOS character.

**Comment by svenefftinge** [comment]
This was a tough one, as I couldn't solve this using the antlr lexer. After trying for a couple of hours without success I gave JFlex (jflex.org) a try and was able to solve the issue with it.

As a result there is now an additional *.flex grammar next to the *.xtext grammar, and another project (xtextgenerator), that contains the enhancement to the language generator.

**Comment by svenefftinge** [comment]
Btw. with the new lexer, we don't need any tricks with hidden() anymore. :-)
