### ISSUE TITLE
pom error with Eclipse 2018-12

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#361]
@kittaakos After pulling the updates to change target to Eclipse 2018-12, I get this error in the com.ge.research.sadl pom.xml file (and in other pom files). Should I need to install this?

Multiple annotations found at this line:
	- Project configurator "org.eclipse.xtend.m2e.xtendConfigurator" required by plugin execution "org.eclipse.xtend:xtend-maven-plugin:2.15.0:testCompile (execution: 
	 default, phase: generate-test-sources)" is not available. To enable full functionality, install the project configurator and run Maven->Update Project Configuration.
	- Project configurator "org.eclipse.xtend.m2e.xtendConfigurator" required by plugin execution "org.eclipse.xtend:xtend-maven-plugin:2.15.0:compile (execution: default, 
	 phase: generate-sources)" is not available. To enable full functionality, install the project configurator and run Maven->Update Project Configuration.

**Comment by kittaakos** [comment]
I have no idea; one has to investigate it. If it's me, please assign the ticket.

**Comment by kittaakos** [comment]
@crapo, did you figure out a solution? If no but the Maven build works from the terminal, you can try to adjust the Maven validation in the preferences; use `warnings` instead of `errors` for now. I did not try it though but bumping up to `Tycho 1.3.0` might have an impact on the POMs.

**Comment by crapo** [comment]
I did not make progress on this. One effect of moving up to Tycho 1.3.0 is that the Maven proxy settings for firewalls must include https, but I don't see how that affects the poms. The error on plugins about missing "Project configurator 'org.eclipse.xtend.m2e.xtendConfigurator" isn't the only one. The pom for reasoner-api and reasoner-impl have the error:

Multiple annotations found at this line:
	- Project configurator "org.sonatype.m2e.mavenarchiver.jararchiverconfigurator" required by plugin execution "org.apache.maven.plugins:maven-jar-plugin:2.4:jar 
	 (execution: default-jar, phase: package)" is not available. To enable full functionality, install the project configurator and run Maven->Update Project Configuration.
	- Project configurator "org.eclipse.m2e.wtp.jaxrs.configurator" required by plugin execution "org.apache.maven.plugins:maven-jar-plugin:2.4:jar (execution: default-jar, 
	 phase: package)" is not available. To enable full functionality, install the project configurator and run Maven->Update Project Configuration.

**Comment by kittaakos** [comment]
I have checked out the `development` branch, reloaded the new target platform; I have zero errors in the POMs. It could be some firewall related issue on your side.

**Comment by kittaakos** [comment]
I did another check on my Windows 10 image, cloned the project, checked out the `development` branch, set the new target platform, ran the MWE2 workflow; no errors.

**Comment by crapo** [comment]
I cloned repo sadlos2, installed Java 8, Eclipse DSL 2018-12, set target, cleaned and rebuilt on a Ubuntu machine over the weekend. I ended up with the same pom.xml error in the poms as I have a work on my Windows machine.

**Comment by kittaakos** [comment]
I am using the following m2e and Tycho features in Eclipse:
![screen shot 2019-02-25 at 15 12 13](https://user-images.githubusercontent.com/1405703/53343089-d1e13200-390f-11e9-88ad-e4b31af29e1d.jpg)

**Comment by crapo** [comment]
That's probably helpful. I have
M2E - Maven Integration for Eclipse 1.10.0.20181127-2120
m2e logback configuration 1.01.0.20181127-2120

I do not have 
m2e slf4j
Tycho Project Configurators

Do you suggest installing from Eclipse Marketplace or?

**Comment by kittaakos** [comment]
> Tycho Project Configurators

Eclipse offered me to install Tycho when I wanted to use the m2e feature for the first time. As I said, I never used the Oomph installer but [here are the steps](https://wiki.eclipse.org/Developing_Tycho#Using_the_Eclipse_Installer_.28Oomph.29) to get Tycho inside Eclipse. I hope it helps.

**Comment by crapo** [comment]
That looks like installation of Tycho source code for Tycho developers. It seems to preclude downloading Eclipse DSL version.

**Comment by kittaakos** [comment]
Can you try this p2 update site: http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.8.0/N/0.8.0.201409231215/

I have copied it from my Eclipse > Preferences > `Install/Update` > `Available Software Sites` > `org.sonatype.tycho.repository`.

**Comment by crapo** [comment]
I've made some observations. I inadvertently selected dsl-2018-09 as the Eclipse version when trying an install using Eclipse Installer. When I did a Maven import existing projects, I got a dialog that asked me if I'd like to setup Maven plugin connectors:
![image](https://user-images.githubusercontent.com/1186278/53496338-df153280-3a6f-11e9-8e35-80d30a8651f5.png)
followed by a dialog asking if I'd like to install Tycho Project Configurators:
![image](https://user-images.githubusercontent.com/1186278/53496396-fe13c480-3a6f-11e9-8370-27c7c1dcccb2.png)
When I did the same with Eclipse Installer version dsl-2018-12, I did not get either of these and ended up with the m2e connector problems. Note that version 2018-09 gives warnings because the target version is 2018-12.
This is not entirely repeatable. I repeated with version 2018-09 and got the same behavior. However, when I repeated with version 2018-12, I did not get the pom errors from missing m2e connectors, even though I had gotten the error after direct installations of dsl-2018-12 on both Windows and Ubuntu.

**Comment by kittaakos** [comment]
I did the followings (on macOS):
- Download [Eclipse IDE for Java and DSL Developers](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2018-12/R/eclipse-dsl-2018-12-R-macosx-cocoa-x86_64.dmg).
- `Import...` > `Maven` > `Existing Maven Projects`.
- Select `.sadl3/com.ge.research.sadl.parent/`.

![screen shot 2019-02-28 at 08 45 46](https://user-images.githubusercontent.com/1405703/53550001-fcaccf80-3b35-11e9-8b1c-b1f43e83e9cd.jpg)

![screen shot 2019-02-28 at 08 49 55](https://user-images.githubusercontent.com/1405703/53550033-0f270900-3b36-11e9-808c-7ade9323147f.jpg)
 - Install and restart.
 - Reset the Git repository state: `git clean -ffxqd && git reset --hard`. For some reason, m2e messes it up.
 - Load and set the TP.
 - Done. ✨ 

![screen shot 2019-02-28 at 09 05 17](https://user-images.githubusercontent.com/1405703/53550859-0e8f7200-3b38-11e9-80a3-c0b7195a825b.jpg)


If it did not prompt you to install the Maven plug-in connectors, it could be some firewall issue.
I am afraid there is not much I can do with this issue, as you can see it worked fine installing everything from scratch.

**Comment by kittaakos** [comment]
I think we can close this; we have already switched to Eclipse 2020-03.

**Comment by crapo** [comment]
agreed
