### ISSUE TITLE
getting model folder path fails for projects imported into workspace but not copied 

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#363]
I imported a project which was created by a git repo clone into a workspace without copying it. (I didn't want to copy it; I wanted changes to be in the local repo so I could push them back.) The call to getConfigMgr in JenaBasedSadlModelProcessor, line 11683, takes one to line 667, where the lWorkspaceRoot is the workspace folder. The value of "root" reutrned on line 672 is as if the project were under the workspace on disk, and is not the correct location.

**Comment by kittaakos** [comment]
I was unable to reproduce the problem with SADL. I did the followings:
 - Open the SADL IDE in Eclipse.
 - `New` > `Project` > `General` > `Project`.
 - Uncheck `Use default location`.
 - Create a project with a few model files.
 - Delete the project from the workspace but do **not** delete from the file system.
 - Initialize your project as a Git repository. (Navigate to your project and execute `git init`.)
 - Import the project as an existing project.
 - When I change the model in Eclipse, it changes in the Git repository I have imported.

Although I have a proposal for this malfunction (see below) it is just a guess until I have more input for the problem.

----

@crapo, the code you are referring is perhaps out of sync. Can you please confirm whether these are the lines you have referenced? As the current state of the `development` branch:

`JenaBasedSadlModelProcessor` line `11683`:
https://github.com/crapo/sadlos2/blob/866b14fe7d7805180f4c1e70c84d399f3315bf43/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L11683

`JenaBasedSadlModelProcessor ` line `667`:
https://github.com/crapo/sadlos2/blob/866b14fe7d7805180f4c1e70c84d399f3315bf43/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L667

`JenaBasedSadlModelProcessor ` line `672`:
https://github.com/crapo/sadlos2/blob/866b14fe7d7805180f4c1e70c84d399f3315bf43/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L672

If you hit a breakpoint inside the following block, it means you have already reached the fallback logic for the headless toolchain: https://github.com/crapo/sadlos2/blob/866b14fe7d7805180f4c1e70c84d399f3315bf43/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L665-L674 

See the corresponding comment: https://github.com/crapo/sadlos2/blob/866b14fe7d7805180f4c1e70c84d399f3315bf43/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L664

----

**Proposed solution:**

I think this is not a SADL issue. It is just a guess, but your extension language most likely does not have the correct `SadlProjectHelper` binding and it falls back to the default implementation.

The UI module of your extension language must use the Eclipse-based helper:
https://github.com/crapo/sadlos2/blob/866b14fe7d7805180f4c1e70c84d399f3315bf43/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/SADLUiModule.xtend#L148-L150
And the IDE module should rebind the IDE project helper:
https://github.com/crapo/sadlos2/blob/866b14fe7d7805180f4c1e70c84d399f3315bf43/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ide/src/com/ge/research/sadl/ide/SADLIdeModule.xtend#L93-L95

**Comment by crapo** [comment]
@kittaakos , I have a reproducible case of this. Can we look at it together?

**Comment by crapo** [comment]
This was related to getting the SADL keywords. They are now static in this branch (and other branches) and this issue is resolved.
