### ISSUE TITLE
Build is broken, change to jflex zip?

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#364]
@tuxji could not do a Maven build with an error on extracting jflex zip. I don't run into it because I already have the jflex jar I guess. However, the AppVeyor build failed on the last push to development on the same error.
 [Build sadlos2 1.0.217 failed](https://ci.appveyor.com/project/crapo/sadlos2/builds/22844513)
Commit 788e632d0b by Andy Crapo on 3/5/2019 5:43 PM: 
Merge branch 'AWC-FinishSadl3' into development 
Configure your notification preferences

**Comment by kittaakos** [comment]
I am looking into this...

**Comment by kittaakos** [comment]
The local Maven build was successful with 788e632d: ` mvn -Dmaven.repo.local=~/Desktop/local-sadl-maven clean verify`. The cause of the problem must be somewhere else...

**Comment by kittaakos** [comment]
I have managed to reproduce it locally after wiping the https://github.com/crapo/sadlos2/blob/development/sadl3/com.ge.research.sadl.parent/.jflex.jar from the FS.

**Comment by kittaakos** [comment]
I can see the following when sniffing into the response message of the download code:
```
cat /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/JFlex5147695485924206982zip
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://jflex.de/jflex-1.4.3.zip">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at jflex.de Port 80</address>
</body></html>

```
