### ISSUE TITLE
[test][releng] We should not run the headless test with a running Eclipse platform

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#370]
The headless tests should be run without a running Eclipse platform. Otherwise, the `com.ge.research.sadl.tests` tests run in a different environment from Eclipse and the command line. Long story short, we have to use `maven-surefire-plugin` instead of `tycho-surefire-plugin`. 

This change affects the `AugmentedTypes` branch.

// cc: @crapo

**Comment by crapo** [comment]
I've lost track--does this issue address the failing tests in ValidationTest?

**Comment by kittaakos** [comment]
> when Maven clean install is run from the command line

Yes, this. Thank you!
