### ISSUE TITLE
Failing test OWL 2 SADL test on the `AugmentedTypes` branch

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#372]
The [`OwlToSadlTest#test04()`](https://github.com/crapo/sadlos2/blob/f75c8706f7734c6e14e3cee739f3097a8eaadf3a/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/owl2sadl/OwlToSadlTest.java#L230-L248) is failing on the AugmentedTypes branch.

```diff
4c4
< import "http://sadl.org/concepts.sadl" as concepts.
---
> import "http://sadl.org/concepts.sadl".
```

I found this when I was working on #370. I am going to `@Ignore` this test, @crapo, can you please check if the test failure is expected or not? Thank you!

**Comment by crapo** [comment]
Test needed to be updated. The "as <alias>" is only added now if the OWL file does not have a prefix specified for the namespace.
