### ISSUE TITLE
constraints on External Equation arguments

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#376]
@kittaakos , can you help me with this? This issue is on branch AugmentedTypes. Charge to ASKE.
Given this example:
[SemanticConstraintsExample.sadl.txt](https://github.com/crapo/sadlos2/files/3393729/SemanticConstraintsExample.sadl.txt)

![image](https://user-images.githubusercontent.com/1186278/61240447-3ceca300-a70f-11e9-978b-15217bfdfa4b.png)

the use of the name of an argument, e.g., "smallerRadius" in lines 5 and 8, is resolved when an Equation but not resolved when an External. Similarly for use of name "alt" in lines 14 and 17-18. Resolved and correctly hyperlinked in 17-18 but not in line 14. I don't see any difference in handling in DeclarationExtensions..

**Comment by crapo** [comment]
Works now. @kittaakos , if you have time please add as test case.

**Comment by kittaakos** [comment]
> if you have time please add as test case.

Can you please this to `com.ge.research.sadl.tests.scoping.SadlLinkingTest` as a test case?
```java
	@Test
	def void testExternalEquationStatement_GH_376() {
		'''
		uri "http://sadl.org/SemanticConstraintsExample.sadl" alias SemanticConstraintsExample.
		
		Circle is a class described by radius with values of type float.
		
		Equation areaBetweenConcentricCircles(float [largerRadius], float [smallerRadius] (<largerRadius> > <smallerRadius>)) returns float :
			return PI*(<largerRadius>^2 - <smallerRadius>^2).
		
		External areaBetweenConcentricCircles2(float [largerRadius], float [smallerRadius] (<largerRadius> > <smallerRadius>)) returns float :
			"uri".
		
		Air is a class, described by altitude with values of type UnittedQuantity,
			described by temperature with values of type UnittedQuantity.
		
		External troposphereTemperature(UnittedQuantity [alt] (altitude of some Air and unit of <alt> is "ft" and ^value of <alt> <= 36152))
			returns UnittedQuantity (temperature of the Air): "uri".
		
		Equation stratosphereTemperature(UnittedQuantity [alt] (altitude of some Air and unit of <alt> is "ft" and
			^value of <alt> > 36152 and ^value of <alt> <= 82345))
				returns UnittedQuantity (temperature of the Air) : return (a UnittedQuantity with ^value 389.98, with unit "F").
		'''.assertLinking[sadl]
	}
```

**Comment by crapo** [comment]
Done! Thanks for providing the test.
