### ISSUE TITLE
Use of prefixes in SadlResource names causes errors

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#40]
If all SadlResource names are prefixed, the name resolution no longer works. This can be reproduced easily by the test mySimpleClassAsQnDeclarationCase in SadlModelManagerProviderTest. This came to light when testing the SadlImportManagerProcessor.

**Comment by svenefftinge** [comment]
See https://github.com/crapo/sadlos2/commit/779c0438d7e70201537675d17a9cd2afa154256f
