### ISSUE TITLE
From where to clean Jena Policy File

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#41]
I have added code to the JenaBasedSadlModelProcessor.onGenerate to add the mapping from the model URI to the generated OWL file to the OwlModels (src-gen folder) ont-policy.rdf file, used by Jena to resolve imports. However, this file also needs to be cleaned so that mappings for SADL files, and eventually external references, that have been deleted or had their URI changed do not remain forever in the policy file. In Xtext 2.4 I could do that from the builder during the clean task. How do I do this with the current generator architecture?

**Comment by svenefftinge** [comment]
We would need to register a Builder Participant to get called on removed resources. then we would need to remove the respective entries and delete the file if no more information is included.
In a future Xtext version (2.10) I want to provide this information also for the regular generator hook.

**Comment by crapo** [comment]
Humm... The ont-policy.rdf file gets removed as part of the clean, and I've added code to regenerate it from scratch whenever it doesn't exist, so maybe this is the right approach?

**Comment by svenefftinge** [comment]
We will also need to remove entries when elements or whole files get removed. I don't think that works already.

**Comment by crapo** [comment]
I think this works--the ont-policy.rdf file is deleted and regenerated by clean/build.
