### ISSUE TITLE
get a list of reserved words

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#43]
Is there an easy, programmatic way to get a list of reserved words in the SADL+SRL grammar? I mean words that would need a "^" in front of them if they were used as a concept name.

**Comment by svenefftinge** [comment]
Yes, you need to inject the IGrammarAccess and use org.eclipse.xtext.GrammarUtil.getAllKeywords(Grammar) with the contained grammar.

**Comment by crapo** [comment]
Thanks for the explanation. We should now be able to do this.
