### ISSUE TITLE
Equation and External in SADL grammar

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#45]
There are two types of equations definition statements. The first is a complete equation definition, meaning that the details of the computation are included. It is of the form:
Equation AreaOfRectangle(float h, float w) returns float: h * w.
The second form only identifies the name and signature of the equation along with its unique identifier (URI) and optionally where to get the equation. This supports the definition of equations in a more powerful and visually-friendly equation language.
External RectArea(float h, float w) returns float: “http://sadl.org/externals#AreaOfRect” located at “file:///c:...”.
The “located at …” is optional.

**Comment by svenefftinge** [comment]
As a follow up to our offline discussion, I am still a bit fuzzy about the meaning of the URI. I wonder why you need to explicitly specify the URI for the external version, as it already has an implied URI based on the file it lives in and the name of the equation.

E.g.

    uri "http://sadl.org/externals".
    External AreaOfRect(float h, float w) returns float.

Would result in a equation declaration with the URI “http://sadl.org/externals#AreaOfRect”.
Or is the URI meant to point to the implementation this signature forwards to? Looks like the location information is meant to do that, so I don't get the role of the URI.

**Comment by svenefftinge** [comment]
Shall it be possible to overload Equation? I.e. should I be able to write

    Equation foo(float h, float w) returns float : h*w
    Equation foo(float h) returns float : h*42

**Comment by svenefftinge** [comment]
A type can have a QNAME, like foo:bar.

So using the ':' after the return type introduces an ambiguity, as it is not clear whether:

    Equation foo() returns  a:b:c.

means

    returns a : b:c.

or 

    returns a:b : c.

I recommend to use another separator.

**Comment by svenefftinge** [comment]
alternatively we could make the QName rule a lexer rule, such that the whitespace can tell the two variants apart and that "a:b:c" will be seen as one qname.

**Comment by svenefftinge** [comment]
I assume the scoping will be similar to the one in rules, with the difference that there are no free variables, but instead the parameters will be added to the scope. Correct?

**Comment by crapo** [comment]
The uri is necessary for External because there is the uri of this thing, consisting as you note of the uri of the model (namespace) and the name of the equation. The uri given for the equation is an external reference, which will necessarily be different. The first is the uri of this reference to an external, the later the identity of the external.

I do not think that we want to allow overloading of equations. This is not object-oriented in that sense.

Fuzzy on the ambiguity of the ":" unless it is with the ":" in the URI's of any concepts used in the specification of the computation.
