### ISSUE TITLE
Rule pattern connectives

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#46]
Lots and lots of existing rules have statements on separate lines with no other junction (no “and”).
Rule Rule_Name
    given
        x is a Thingy  
    then
        intVal of x is abs(-1)
        flVal of x is abs(-1.0)
        dblVal of x is abs(-1.0).
It would be highly desirable to continue to allow clauses to be given this way without an explicit "and".

**Comment by svenefftinge** [comment]
I have no good idea how to make this work, unfortunately.

**Comment by svenefftinge** [comment]
I will try to solve this by allowing NL as an alternative in this case. Let's see if I can make it work.

**Comment by svenefftinge** [comment]
No, that won't work, as I would have to change the set of hidden rules for the full expression, which would dissallow newlines everywhere or force us to list them everywhere they could ocure.

**Comment by crapo** [comment]
resigned to the improvement to the rule grammar that rule elements must be conjunctively (or disjunctively) connected with explicit junctions.
