### ISSUE TITLE
leading digit required for decimal literal

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#49]
SadlRuleParserTest.xtend has new test case testInstanceDeclaration_06 which illustrates that a leading digit is required for a decimal fraction less than 1.0. This was not the case in SADL2 so there is a usability and a backwards compatibility issue.

**Comment by svenefftinge** [comment]
fixed with https://github.com/crapo/sadlos2/commit/a96edd8196c6e39f6b5da08359386627828336f9
