### ISSUE TITLE
Unwanted Dependency introduced to '/com.ge.research.sadl'

### ISSUE THREAD

**Issue by svenefftinge** [crapo/sadlos2#50]
The sadl3 runtime project '/com.ge.research.sadl' just recently got dependencies to org.eclipse.ui and org.eclipse.core.resources. Both of which will make this project unusable in-non eclipse scenarios.

**Comment by crapo** [comment]
I assume we can sort that out in our meeting today. I don't think it was intentional.

**Comment by svenefftinge** [comment]
We've removed most dependencies today.

**Comment by svenefftinge** [comment]
see also #68
