### ISSUE TITLE
error in lexer-based converter

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#52]
Got this error when doing initial build of project (project attached). The last error is an out of memory error.
[TestSadlIde20160322.zip](https://github.com/crapo/sadlos2/files/184307/TestSadlIde20160322.zip)

404139 [Worker-8] WARN  org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter  - Only terminal rules are supported by lexer based converters but got DNAME which is an instance of ParserRule

!ENTRY org.apache.log4j 2 0 2016-03-22 10:24:50.051
!MESSAGE org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter  - Only terminal rules are supported by lexer based converters but got DNAME which is an instance of ParserRule

!ENTRY org.eclipse.core.jobs 4 2 2016-03-22 10:24:51.956
!MESSAGE An internal error occurred during: "Building workspace".

**Comment by crapo** [comment]
I think I found a loop that was causing memory issues. I pushed a fix and haven't seen any memory errors since.

**Comment by svenefftinge** [comment]
The warning message regarding regard the lexer is harmless and has nothing to do with the out of memory issue.
