### ISSUE TITLE
getting project folder in onGenerate

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#53]
In the JenaBasedSadlModelProcessor, on Generate method, I think I need to get the project folder in order to create some basic content (ont-policy.rdf, configuration.rdf) if they don't already exist. What I'm doing currently only works if the project is under the workspace folder on disk. Is this possible? Not desirable?

**Comment by svenefftinge** [comment]
In eclipse (and we can make sure that this will also hold in other environments) the resource URI is always a so called platform:/resource/ URI. The second segment denotes the project name and the rest is a relative path to the project root. 
EMF maintains a platform resource map (in org.eclipse.emf.ecore.plugin.EcorePlugin.getPlatformResourceMap()) which can be used to resolve such a platform resource URI to a file URI. 

An even better approach would be to rely on URIs completely and simply use the URIConverter associated with the ResourceSet (resource.getResourceSet().getURIConverter()) to load and save files. That way such operations will go through Eclipse's resource model.

**Comment by crapo** [comment]
This is now working.
