### ISSUE TITLE
onValidate and onGenerate with clean/build all

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#64]
When a clean/build all is requested everything gets cleared from the project build directory, then onValidate appears to get called for all .sadl files, then onGenerate is called. The construction of the ont-policy.rdf mapping file takes place in the onGenerate method, but the onValidate methods need to know the mappings of imported models so as to be able to load the right ontologies (imports) in the Jena OntModel. Consequently onValidate fails to be able to do the deeper semantic checking. Not sure of the  best solution...

**Comment by svenefftinge** [comment]
You need to do all the analysis in onValidate

**Comment by crapo** [comment]
If the ont-policy.rdf file is cleaned then I must have some way to know what imports what. I think this is in the Xtext index. How do I find what is imported by a given resource imported by this model?

**Comment by svenefftinge** [comment]
We discussed in our meeting, that navigating through SadlModel.getImports()....getImportedResource recursively is the way to go. We will take care of external models (non SADL) later and they will be resolvable though the same means.

**Comment by crapo** [comment]
This works for an actual IDE project but there's an issue if run from a JUnit test where there are imports. For example, in the RequirementsModelProcessorTestSampleReqProject, testExample_15_1, model "http://assert/Properties" is imported by "http://ont.sample/SYSTEM", which in turn is imported by  "http://req.sample/SAMPLE_REQ__15_1__Example". When onValidate is called on the last model, in order to do deep semantic checking, I need to be able to do the Jena import of the second (direct import) and the first (indirect import). When running from the actual IDE, I can use the getImportedResource to get the URI of the import and the Resource to derive its URL and so load the Jena model which will have been written to disk. But when a JUnit test the Jena model will not have been persisted by the onValidate that ran on it. 
It seems there are two choices. One could pass the Jena models into the ModelProcessor from the test code prior to the call to onValidate. Or one could create a ModelProcessor for each import, call onValidate, and then get the Jena model from that ModelProcessor. Do either of these make sense? One more than the other?

**Comment by svenefftinge** [comment]
You should never rely on generated files during processing, because they might not be there (clean build) pr outdated (incremental build). 
I think the right thing to do would be to reuse the OntModel created for imported resources. I have written a small utility that allows you to attach an OntModel to an XtextResource. 

You need to do two things:
1) In the processor when the OntModel is ready, you attach it to the resource:
  `OntModelProvider.attach(model.eResource(), theJenaModel);`
2) When doing the imports instead of going through jena resources and loading them, you add the ontmodel from the imported XtextResource. Something like this:
```
Iterator<SadlImport> impitr = implist.iterator();
while (impitr.hasNext()) {
	SadlImport simport = impitr.next();
	SadlModel importedResource = simport.getImportedResource();
	if (importedResource != null) {
		OntModel importedOntModel = OntModelProvider.find(importedResource.eResource());
		getTheJenaModel().add(importedOntModel);
	}
}
```

**Comment by GEGlobalResearch** [comment]
That seems a fabulous solution, working for JUnit tests as sell as the real IDE! Thank you!!

**Comment by crapo** [comment]
Actually, doesn't work for actual IDE either as the OWL model has potentially been wiped out on clean.

**Comment by crapo** [comment]
Works great for the JUnit tests, after adding calls to JenaBasedSadlModelProcessor for each SADL model in the test. However, for the IDE the problem remains to create the Jena OntModel for each import, direct or indirect, as there is no call to onValidate for these Resources. It would require that a JenaBasedSadlModelProcessor instance be created and onValidate called for each of these so that the OntModel is with the XtextResource.

**Comment by crapo** [comment]
This doesn't seem to work for the IDE. A clean build still fails to find OntModels for imports so the semantic checking fails. It seems that even the Xtext linking fails for some names. I can perhaps illustrate this the next time we have an opportunity to discuss in WebEx. This is a show stopper for being able to become the basis for the released tool.

**Comment by crapo** [comment]
This seems to be working much better now. Not sure if anything changed. Maybe I misunderstood what was happening. It is the case that a lot of onValidate calls occur. There is a call to onValidate for an import, as needed to generate the OntModel. But it still gets called again "for it's own sake" if you will.

**Comment by crapo** [comment]
I think this is all working satisfactorily now.
