### ISSUE TITLE
On-going packaging issues

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#66]
packaging seems to breakdown for us on a regular basis I will attach some of the problems.

**Comment by crapo** [comment]
When I run "SADL mvn clean install.launch" in com.ge.research.sadl.parent, I get this failure:

**Comment by crapo** [comment]
When I run "SRL mvn clean install.launch" in the com.ge.research.sadl.requirements.parent, I get this failure:
[INFO] Resolving class path of MavenProject: com.ge.research.sadl.requirements:com.ge.research.sadl.requirements.ui.tests:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.research.sadl.requirements.ui.tests\pom.xml
[INFO] Computing target platform for MavenProject: com.ge.research.sadl.requirements:com.ge.research.sadl.requirements.toprolog:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.research.sadl.requirements.toprolog\pom.xml
[INFO] Resolving dependencies of MavenProject: com.ge.research.sadl.requirements:com.ge.research.sadl.requirements.toprolog:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.research.sadl.requirements.toprolog\pom.xml
[WARNING] The following locally built units have been used to resolve project dependencies:
[WARNING]   com.ge.research.sadl.jena/3.0.0.201604182110
[WARNING]   com.ge.research.sadl/3.0.0.201604182110
[WARNING]   com.ge.research.jena/3.0.0.201604182110
[INFO] Resolving class path of MavenProject: com.ge.research.sadl.requirements:com.ge.research.sadl.requirements.toprolog:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.research.sadl.requirements.toprolog\pom.xml
[INFO] Computing target platform for MavenProject: com.ge.research.sadl.requirements:com.ge.aviation.sadl.requirements.assert-perspective:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.aviation.sadl.requirements.assert-perspective\pom.xml
[INFO] Resolving dependencies of MavenProject: com.ge.research.sadl.requirements:com.ge.aviation.sadl.requirements.assert-perspective:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.aviation.sadl.requirements.assert-perspective\pom.xml
[WARNING] The following locally built units have been used to resolve project dependencies:
[WARNING]   com.ge.research.sadl.ui/3.0.0.201604182110
[WARNING]   com.ge.research.sadl/3.0.0.201604182110
[WARNING]   com.ge.research.jena/3.0.0.201604182110
[WARNING]   com.ge.research.sadl.ide/3.0.0.201604182110
[INFO] Resolving class path of MavenProject: com.ge.research.sadl.requirements:com.ge.aviation.sadl.requirements.assert-perspective:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.aviation.sadl.requirements.assert-perspective\pom.xml
[INFO] Computing target platform for MavenProject: com.ge.research.sadl.requirements:com.ge.research.sadl.requirements.feature:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.research.sadl.requirements.feature\pom.xml
[INFO] Resolving dependencies of MavenProject: com.ge.research.sadl.requirements:com.ge.research.sadl.requirements.feature:2.0.0-SNAPSHOT @ C:\Users\200005201\sadl3-master5\git\requirements\com.ge.research.sadl.requirements.parent\com.ge.research.sadl.requirements.feature\pom.xml
[INFO] {osgi.ws=cocoa, osgi.os=macosx, osgi.arch=x86_64, org.eclipse.update.install.features=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.ge.research.sadl.requirements.feature.feature.group 2.0.0.qualifier
[ERROR]   Missing requirement: com.ge.research.sadl.feature.feature.group 3.0.0.201604141726 requires 'com.ge.research.sadl [3.0.0.201604141532]' but it could not be found
[ERROR]   Cannot satisfy dependency: com.ge.research.sadl.requirements.feature.feature.group 2.0.0.qualifier depends on: com.ge.research.sadl.feature.feature.group 0.0.0

**Comment by svenefftinge** [comment]
I think I've fixed these issues this morning.

**Comment by svenefftinge** [comment]
This is solved now.
