### ISSUE TITLE
Location of declarations in SADL name indexing/linking

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#67]
A **class definition** (of <myclass> can be one of the following:
Level 1: duplication of level 1 declarations should at least generate a warning
- <myclass> is a [top-level] class.
- <myclass> is a type of <superclass>.
- {<myclass>, ....} are [top-level] classes.
- {<myclass>, ....} are types of <superclass>.

Level 2: these can occur when there is a level 1 declaration, in which case it is neither an error nor a declaration, but is adding additional information
-  A <superclass> is a <myclass> only if ....
- <myclass> is the same as ....

An **instance definition** (of <inst>) can be one of the following:
Level 1: duplication is not an error as one might wish to declare an instance to belong to more than one class in separate statements
- <inst> is a <class>.
- {<inst>, <inst2>, ...} are instances of <class>.     // this isn't currently in the grammar but is desirable if easy to add

Level 2: If an instance is not declared in a Level 1 statement, these are valid declarations
-  ... must be one of {<inst>, <inst2>,...}.   // this and the next could occur when <inst> has already been defined by one of the above--can there be precedence in declaration?
-  ... can only be one of {<inst>, <inst2>,...}

A **property definition **(of <prop>) can be one of the following:
Level 1: duplication is an error or warning
- <prop> is a property.
- <prop> is a type of <superprop>.
- <prop> is a type of annotation.

Level 2: if not defined by a Level 1 statement, the first of these is a property declaration
-  ... is a class (or ... is a type of <class>), described by <prop> ...
- <prop> describes <domain>...
-  relationship of <domain> to <range> is <prop>.  // "Relationship" 

**Variable declarations:
In requirements: left **or right side of where clause, left or right side of context statement
In sadl rules: first occurrence is declaration
In sadl queries: first occurrence graph patterns (NOT in "select <var-list>..")

**Comment by svenefftinge** [comment]
> Level 2: these can occur when there is a level 1 declaration, in which case it is neither an error nor a 
> declaration,  but is adding additional information

So when there is no corresponding level 1 declaration, it is an error?

**Comment by GEGlobalResearch** [comment]
If possible, this should not be an error. Rather if level 2 occurs without a level 1 declaration than the level 2 statement is an acceptable declaration. This is OK in the OWL model generation.

**Comment by svenefftinge** [comment]
I have added some test cases, which are all green. 
Could you add failing test cases and set them to @Ignore, so I better understand what to fix here?

**Comment by crapo** [comment]
I added some tests, currently failing and ignored, to SadlLinkingTest.xtend.
