### ISSUE TITLE
Save Trigger

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#7]
The JenaBasedSadlModelProcessor class can have a save() method which should be called when the SADL model is written to disk. This will trigger writing of the OWL model in the OwlModels folder, assuming a valid SADL model. It can also trigger the writing of an ont-policy.rdf file, which should really only reflect changes which are saved. Is this the correct approach? And if so from where is this save() called?

**Comment by svenefftinge** [comment]
The save should be called from within 'onGeneration' in the JenaBasedModelProcessor.
The generation of the ont-policy file cannot be done like this, as the jena model might be incomplete during an incremental build. Instead we should directly update the file using text manipulation.

**Comment by svenefftinge** [comment]
Closing this as I don't see any outstanding actions.
