### ISSUE TITLE
Duplicated names (URIs) in independent projects

### ISSUE THREAD

**Issue by GEGlobalResearch** [crapo/sadlos2#77]
If I have two projects open which have the same SADL file name, URI, or prefix, this is detected and an error generated. The error message says that the filename must be unique in a project but the project referenced is not the same one. The code that generates these errors is below. I thought that this would not be a problem unless one project depended upon the other, making them part of the same "space of names". Is the error generation wrong or is my understanding of scoping wrong?

		val thisResourceDescription = resourceDescriptionManager.getResourceDescription(model.eResource)
		val allModels = resourceDescriptionsProvider.getResourceDescriptions(model.eResource.resourceSet).getExportedObjectsByType(SADLPackage.Literals.SADL_MODEL)
		for (modelDescription : allModels.filter[EObjectURI.trimFragment != thisResourceDescription.URI]) {
			if (modelDescription.name.toString == thisUri) {
				error("This URI is already used in '" + modelDescription.EObjectURI.trimFragment + "'", SADLPackage.Literals.SADL_MODEL__BASE_URI, INVALID_MODEL_URI)
			}
			if (model.alias !== null && modelDescription.getUserData(ResourceDescriptionStrategy.USER_DATA_ALIAS) == model.alias) {
				error("The alias '"+model.alias+"' is already used in '" + modelDescription.EObjectURI.trimFragment + "'", SADLPackage.Literals.SADL_MODEL__ALIAS, INVALID_MODEL_ALIAS)
			}
			if (modelDescription.EObjectURI.trimFragment.lastSegment == simpleFileName) {
				error("The simple filename (" + simpleFileName + ") is already used by model '" + modelDescription.EObjectURI.trimFragment + "'; filenames must be unique within a project.", SADLPackage.Literals.SADL_MODEL__BASE_URI, INVALID_MODEL_FILENAME)
			}
		}

**Comment by svenefftinge** [comment]
We decided to go with this as a sort of "good-enough for now" approach. It checks duplication globally and doesn't check project scopes.
