### ISSUE TITLE
HighlightingCalculator

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#8]
Based on the way that highlighting was refactored by Karsten to work in the SADL 2 code, the ResourceSet will store the type (individual, class, dataproperty, objectproperty, annotationproperty) of each concept defined in a Resource. If a SADL file imports an external OWL file (not from SADL in this or a project upon which this project depends), the concepts and their types are available by loading the OWL file into memory and querying. Should a Resource in the ResourceSet be created for an external OWL file when it is added to the external mappings? Or should it be added the first time that it is actually added to a SADL file as an import? And where should the method for retrieving the concepts and types from the OWL model be located?

**Comment by svenefftinge** [comment]
We need to be able to load all participating files as EMF Resources, the contents must at least contain all declared OWL concepts, that can be referenced from SADL

**Comment by crapo** [comment]
I can easily provide you with code that will use Jena to load an OWL Resource and give you all of the concepts and their type. If the SADL 2 code seems convoluted we can just do a clean implementation.

**Comment by svenefftinge** [comment]
Could you also (in addition of the code, which I think I'll find in the repository) provide a short description of the requirements?
I.e. a list of how the different concepts should be colored.

**Comment by crapo** [comment]
Class names, including prefix, are colored dark blue bold.
Instances are colored lighter blue.
Object and datatype properties are colored green bold.
Annotation properties are colored green, not bold (lighter?).

**Comment by svenefftinge** [comment]
fixed
