### ISSUE TITLE
Any named list should be of type CLASS

### ISSUE THREAD

**Issue by GEGlobalResearch** [crapo/sadlos2#85]
I think that we want all  named "<type> List" EObjects to be of OntConceptType CLASS. Or maybe we need new OntConceptType for CLASS_LIST and DATATYPE_LIST. I was going for CLASS...

I inserted these two lines at 165 in DeclarationExtensions.xtend:
SadlClassOrPropertyDeclaration case e.superElement!==null && e.superElement.isList : 
    OntConceptType.CLASS

and added the method isList:
//  protected def boolean isList(SadlTypeReference typeRef) {
//      typeRef != null && typeRef instanceof SadlPrimitiveDataType && typeRef.list == true
//  }

This goes into infinite recursion, so clearly I don't understand what the xtend code is doing...

Test case "testIntList" added to DeclarationExtensionsTest.xtend.

**Comment by crapo** [comment]
this is OBE--already implemented.
