### ISSUE TITLE
Non-OWL content of a SADL model

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#9]
A SADL model can contain non-OWL content that falls into two categories. Queries and tests are only stored in memory. However, rules need to be translated into the syntax required by the target reasoner, and saved to disk in the OwlModels folder. In the current implementation, this happens in two stages. The processing of the parse tree passes constructs to the IntermediateFormTranslator, which creates an in-memory representation that is then passed to the translator associated with the target reasoner on save(). I assume that these calls happen from the model processor, e.g., JenaBasedSadlModelProcessor. Does this make sense?

**Comment by svenefftinge** [comment]
Not sure, we basically have to life cycle callbacks now. 
1) onValidation
Here we can resolve all the links, create the OntModel and report errors.
2) onGeneration
Here we can do code generation (calling save on the Jena Model and generate/update other files
