### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by svenefftinge** [crapo/sadlos2#95]
With the current state seven tests fail for me.

**Comment by svenefftinge** [comment]
<img width="542" alt="screen shot 2016-07-14 at 11 26 10" src="https://cloud.githubusercontent.com/assets/372735/16834805/d422cc00-49b5-11e6-94a8-4ba9d2c429b8.png">

**Comment by crapo** [comment]
I fixed these failing tests. I didn't understand why the Maven build still was completing even though the tests were run (not @Ignore) and failed.
