### ISSUE TITLE
Quick fix for ambiguous reference to imported name

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#98]
Issue #96 identifies reference ambiguity and puts an error marker on the ambiguous name. It is desired that there be an associated quick fix that lists the qualified names that could be used to disambiguate the reference. For example, if model C imports A which defines Car and also imports B which defines car, with prefixes "a" and "b" respectively, and they model C says "MyCar is a Car." the quick fix associated with the ambiguous error on "Car" would contain two choices, "a:Car" and "b:Car".

**Comment by crapo** [comment]
Don't know if fix to #96 will eliminate this problem, but in the IDE if I chose one of multiple identical quick fixes to provide a qualified name for a name that is marked as ambiguous but is not, then an error is created for the qualified name that says "Ambiguously imported name 'Properties.input_1' from 'http://assert/Properties', 'http://assert/Properties'. Please use an alias or choose different names." The quick fixes are then the unqualified names, "change to 'input_1'" but repeated multiple times.

**Comment by svenefftinge** [comment]
oh, right I didn't filter out multiple results of the same element. E.g. when you import the same file more than once through transitive closure. Will fix it ASAP.
